#!/bin/bash
set -euo pipefail
APP="${1:?usage: audit_wave69_physical_uat_preflight.sh <app>}"
RES="$APP/Contents/Resources"
SRC="$RES/source"
LAUNCH="$RES/launch.py"
SERVICE="$SRC/src/binario_marketing/service_wave69_app.py"
UI="$SRC/web/physical-uat-preflight.js"
[[ -f "$SERVICE" && -f "$UI" && -f "$LAUNCH" ]] || { echo 'Wave 69 bundle files missing' >&2; exit 1; }
/usr/bin/grep -q 'service_wave69_app import serve' "$LAUNCH"
/usr/bin/grep -q 'service_wave68_app as base' "$SERVICE"
/usr/bin/grep -q 'binario.marketing.physical-uat-preflight.v1' "$SERVICE"
/usr/bin/grep -q 'physical_gate_eligible' "$SERVICE"
/usr/bin/grep -q 'BUILD_PROVENANCE.json' "$SERVICE"
/usr/bin/grep -q 'physical_uat_candidate' "$SERVICE"
/usr/bin/grep -q 'main-candidate-build' "$SERVICE"
/usr/bin/grep -q '_require_physical_uat_preflight' "$SERVICE"
/usr/bin/grep -q 'runtime.*python' "$SERVICE"
/usr/bin/grep -q 'release-fail-closed' "$SERVICE"
/usr/bin/grep -q 'physical_preflight_is_release_authority' "$SERVICE"
/usr/bin/grep -q 'physical-uat-preflight.js' "$SERVICE"
/usr/bin/grep -q 'data-physical-uat-preflight-wave69' "$SERVICE"
/usr/bin/grep -q 'PREFLIGHT BLOQUEADO' "$UI"
/usr/bin/grep -q 'LISTO PARA INICIAR' "$UI"
/usr/bin/grep -q 'Revalidar preflight' "$UI"
/usr/bin/grep -q 'ready_to_begin_physical_uat' "$UI"
! /usr/bin/grep -q "method:'POST'" "$UI"
! /usr/bin/grep -q "method:'PATCH'" "$UI"
! /usr/bin/grep -q 'setInterval' "$UI"
! /usr/bin/grep -q 'sendBeacon' "$UI"
! /usr/bin/grep -qi 'supabase\|vercel' "$UI"
printf 'WAVE 69 PHYSICAL UAT PREFLIGHT AUDIT PASS\n'
