const wave51AIState={companyId:null,settings:null,providers:[],sessions:[],loading:false,lastSession:null};

function wave51Styles(){
  if(document.querySelector('#wave51-ai-style'))return;
  const style=document.createElement('style');style.id='wave51-ai-style';style.textContent=`
  .w51-ai{border:1px solid #d9d5cc;border-radius:16px;background:#fff;padding:15px;display:grid;gap:12px}.w51-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end}.w51-head h3{margin:0}.w51-badge{font-size:8px;padding:5px 8px;border-radius:999px;background:#efede7}.w51-badge.ok{background:#e6efe7}.w51-grid{display:grid;grid-template-columns:minmax(320px,.75fr) minmax(440px,1.25fr);gap:12px}.w51-config,.w51-work{border:1px solid #e4e0d8;border-radius:12px;padding:12px;display:grid;gap:10px}.w51-form{display:grid;gap:8px}.w51-form .two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.w51-form label{display:grid;gap:4px;font-size:8px;color:#68645d}.w51-form textarea{min-height:74px}.w51-credential{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px}.w51-disclosure{font-size:8px;color:#6a665e;background:#f4f2ed;border-radius:9px;padding:8px;line-height:1.45}.w51-result{display:grid;gap:9px}.w51-summary{padding:11px;background:#f6f4ef;border-radius:10px;font-size:10px;line-height:1.5}.w51-recs{display:grid;gap:6px}.w51-rec{border:1px solid #e2ded5;border-radius:9px;padding:9px;display:grid;grid-template-columns:72px minmax(0,1fr);gap:8px}.w51-rec .priority{font-size:8px;font-weight:700}.w51-rec strong{font-size:10px}.w51-rec p{margin:3px 0;font-size:9px;color:#68645d}.w51-variants{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.w51-variant{border:1px solid #e2ded5;border-radius:10px;padding:9px;display:grid;gap:6px}.w51-variant strong{font-size:10px}.w51-variant p{font-size:9px;white-space:pre-wrap;margin:0}.w51-variant small{font-size:8px;color:#6b675f}.w51-actions{display:flex;gap:7px;flex-wrap:wrap}.w51-history{display:flex;gap:6px;overflow:auto;padding-bottom:2px}.w51-history button{white-space:nowrap;font-size:8px}.w51-empty{border:1px dashed #d3cec4;border-radius:9px;padding:12px;font-size:9px;color:#6c685f}.w51-brief{border:1px solid #e1ddd5;border-radius:10px;padding:10px;display:grid;gap:5px}.w51-brief p{font-size:9px;margin:0;color:#67635c}.w51-provider-note{font-size:8px;color:#706c65}
  @media(max-width:980px){.w51-grid{grid-template-columns:1fr}}@media(max-width:650px){.w51-form .two,.w51-variants{grid-template-columns:1fr}.w51-head{align-items:flex-start;flex-direction:column}}
  `;document.head.append(style)
}

function wave51Company(){return typeof wave47Company==='function'?wave47Company():(typeof opsSelectedCompany==='function'?opsSelectedCompany():null)}
function wave51Provider(){return wave51AIState.providers.find(row=>row.provider===wave51AIState.settings?.provider)||null}
function wave51CreativeOptions(){return (wave49CreativeState?.context?.items||[]).filter(row=>row.creative).map(row=>[row.media.id,row.creative.title||row.media.original_name])}
function wave51CampaignOptions(){return (wave49CreativeState?.context?.campaigns||[]).map(row=>[row.id,row.name])}

async function wave51Load(force=false){
  const company=wave51Company();if(!company){wave51AIState.companyId=null;wave51AIState.settings=null;wave51AIState.sessions=[];return}
  if(wave51AIState.loading)return;
  if(!force&&wave51AIState.companyId===company.id&&wave51AIState.settings)return;
  wave51AIState.loading=true;
  try{
    const [providers,settings,sessions]=await Promise.all([
      opsApi('/api/ai/providers'),
      opsApi(`/api/companies/${encodeURIComponent(company.id)}/ai/settings`),
      opsApi(`/api/companies/${encodeURIComponent(company.id)}/ai/sessions?limit=10`),
      typeof wave49Load==='function'?wave49Load(false):Promise.resolve(null),
    ]);
    wave51AIState.companyId=company.id;wave51AIState.providers=providers;wave51AIState.settings=settings;wave51AIState.sessions=sessions;wave51AIState.lastSession=wave51AIState.lastSession||sessions[0]||null;
  }finally{wave51AIState.loading=false}
}

function wave51Select(labelText,rows,value){const label=opsEl('label','',labelText),select=document.createElement('select');for(const [id,name] of rows){const option=opsEl('option','',name);option.value=id;option.selected=id===(value||'');select.append(option)}label.append(select);return{label,select}}
function wave51Field(labelText,type,value=''){const label=opsEl('label','',labelText),input=document.createElement('input');input.type=type;input.value=value||'';label.append(input);return{label,input}}

async function wave51SaveSettings(fields){const company=wave51Company();if(!company)return;const result=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/ai/settings`,{method:'PATCH',body:{provider:fields.provider.value||null,model:fields.model.value.trim()||null,language:fields.language.value.trim()||'es',brand_voice:fields.voice.value.trim()}});wave51AIState.settings=result;wave51AIState.lastSession=null;opsToast('Configuración de IA guardada')}

async function wave51ConnectProvider(provider,input,button){if(provider==='ollama')return;const key=input.value.trim();if(!key){opsToast('Pega la API key');return}button.disabled=true;try{const row=await opsApi(`/api/ai/providers/${encodeURIComponent(provider)}/connection`,{method:'POST',body:{api_key:key}});input.value='';wave51AIState.providers=wave51AIState.providers.map(item=>item.provider===provider?row:item);opsToast(`${row.name} conectado`);renderMarketingOps()}catch(err){opsToast(err.message)}finally{button.disabled=false}}
async function wave51DisconnectProvider(provider){if(!confirm(`¿Eliminar la credencial ${provider} guardada por Binario?`))return;try{const row=await opsApi(`/api/ai/providers/${encodeURIComponent(provider)}/connection`,{method:'DELETE'});wave51AIState.providers=wave51AIState.providers.map(item=>item.provider===provider?row:item);opsToast('Credencial eliminada');renderMarketingOps()}catch(err){opsToast(err.message)}}

function wave51Config(root){const settings=wave51AIState.settings||{},providerRows=[['','Selecciona provider'],...wave51AIState.providers.map(row=>[row.provider,row.name])],provider=wave51Select('Provider',providerRows,settings.provider||''),model=wave51Field('Modelo','text',settings.model||''),language=wave51Field('Idioma','text',settings.language||'es'),voiceLabel=opsEl('label','','Voz / reglas de marca'),voice=document.createElement('textarea');voice.rows=4;voice.value=settings.brand_voice||'';voice.placeholder='Tono, palabras preferidas, claims prohibidos, estilo…';voiceLabel.append(voice);const form=opsEl('form','w51-form'),row=opsEl('div','two');row.append(provider.label,model.label);form.append(row,language.label,voiceLabel);const save=opsEl('button','primary','Guardar configuración');save.type='submit';form.append(save);form.addEventListener('submit',async e=>{e.preventDefault();save.disabled=true;try{await wave51SaveSettings({provider:provider.select,model:model.input,language:language.input,voice});await wave51Load(true);renderMarketingOps()}catch(err){opsToast(err.message)}finally{save.disabled=false}});provider.select.addEventListener('change',()=>{wave51AIState.settings={...settings,provider:provider.select.value||null};renderMarketingOps()});root.append(form);
  const current=wave51AIState.providers.find(item=>item.provider===(provider.select.value||settings.provider));if(!current){root.append(opsEl('div','w51-provider-note','Elige un provider y escribe explícitamente el modelo que quieres usar.'));return}const status=opsEl('div','w51-provider-note',current.local?'Ollama usa el servicio local de este Mac; Binario no guarda API key.':`${current.configured?'Conectado':'Sin credencial'} · fuente: ${current.source}`);root.append(status);if(!current.local){const cred=opsEl('div','w51-credential'),input=document.createElement('input');input.type='password';input.placeholder='API key · no se guarda en JSON';const connect=opsEl('button','','Guardar en Keychain');connect.type='button';connect.addEventListener('click',()=>wave51ConnectProvider(current.provider,input,connect));cred.append(input,connect);root.append(cred);if(current.configured&&current.source==='keychain'){const disconnect=opsEl('button','','Eliminar credencial de Keychain');disconnect.type='button';disconnect.addEventListener('click',()=>wave51DisconnectProvider(current.provider));root.append(disconnect)}}
}

function wave51ApplyVariant(session,variant){const company=wave51Company(),mediaId=session?.creative_media_id;if(!company||!mediaId){opsToast('Esta sesión no está ligada a un creativo');return}if(!confirm('¿Aplicar este copy/headline/CTA al brief local de Creative Studio? No se publicará nada.'))return;opsApi(`/api/companies/${encodeURIComponent(company.id)}/creatives/${encodeURIComponent(mediaId)}`,{method:'PATCH',body:{primary_copy:variant.copy,headline:variant.headline||null,call_to_action:variant.cta||'LEARN_MORE',stage:'DRAFT'}}).then(async()=>{if(typeof wave49Load==='function')await wave49Load(true);opsToast('Variante aplicada al brief local');opsShowView('content')}).catch(err=>opsToast(err.message))}

function wave51Result(root,session){if(!session){root.append(opsEl('div','w51-empty','Genera una recomendación para ver aquí diagnóstico, próximos pasos, brief y variantes.'));return}const out=session.output||{},box=opsEl('div','w51-result');box.append(opsEl('div','w51-summary',out.summary||'Sin resumen.'));if((out.diagnosis||[]).length){const diag=opsEl('div','w51-brief');diag.append(opsEl('strong','','Diagnóstico'));for(const item of out.diagnosis)diag.append(opsEl('p','',`• ${item}`));box.append(diag)}if((out.recommendations||[]).length){const recs=opsEl('div','w51-recs');for(const rec of out.recommendations){const card=opsEl('div','w51-rec');card.append(opsEl('span','priority',`${rec.priority} · ${rec.area}`));const body=opsEl('div','');body.append(opsEl('strong','',rec.title),opsEl('p','',rec.why),opsEl('p','',`Siguiente: ${rec.next_step}`));card.append(body);recs.append(card)}box.append(recs)}if((out.creative_variants||[]).length){const title=opsEl('strong','','Variantes creativas'),variants=opsEl('div','w51-variants');for(const variant of out.creative_variants){const card=opsEl('div','w51-variant');card.append(opsEl('strong','',variant.label),opsEl('small','',variant.headline||''),opsEl('p','',variant.copy),opsEl('small','',`CTA · ${variant.cta||'—'}`));if(session.creative_media_id){const use=opsEl('button','','Usar en Creative Studio');use.type='button';use.addEventListener('click',()=>wave51ApplyVariant(session,variant));card.append(use)}variants.append(card)}box.append(title,variants)}const brief=out.campaign_brief||{};if(brief.objective||brief.audience||brief.proposition){const card=opsEl('div','w51-brief');card.append(opsEl('strong','','Brief sugerido'));if(brief.objective)card.append(opsEl('p','',`Objetivo: ${brief.objective}`));if(brief.audience)card.append(opsEl('p','',`Audiencia: ${brief.audience}`));if(brief.proposition)card.append(opsEl('p','',`Propuesta: ${brief.proposition}`));if((brief.channels||[]).length)card.append(opsEl('p','',`Canales: ${brief.channels.join(', ')}`));if((brief.kpis||[]).length)card.append(opsEl('p','',`KPIs: ${brief.kpis.join(', ')}`));box.append(card)}box.append(opsEl('div','w51-provider-note',`${session.provider} · ${session.model} · contexto ${String(session.context_sha256||'').slice(0,12)}… · ${opsDate(session.created_at)}`));root.append(box)}

function wave51Work(root){const settings=wave51AIState.settings||{},task=wave51Select('Tarea',[['STRATEGY','Estrategia / prioridades'],['CAMPAIGN','Mejorar campaña'],['CREATIVE','Mejorar creativo']],'STRATEGY'),campaign=wave51Select('Campaña',[['','Selecciona campaña'],...wave51CampaignOptions()],'');const creative=wave51Select('Creativo',[['','Selecciona creativo'],...wave51CreativeOptions()],'');const instructionLabel=opsEl('label','','Instrucción adicional'),instruction=document.createElement('textarea');instruction.rows=4;instruction.placeholder='Ej. prioriza captación de leads sin aumentar presupuesto…';instructionLabel.append(instruction);const form=opsEl('form','w51-form'),targets=opsEl('div','two');targets.append(campaign.label,creative.label);form.append(task.label,targets,instructionLabel);const generate=opsEl('button','primary','Generar con IA');generate.type='submit';generate.disabled=!settings.provider||!settings.model;form.append(generate,opsEl('div','w51-disclosure','Al generar, Binario enviará al provider seleccionado un contexto marketing sanitizado de esta empresa. No incluye PII de contactos, archivos multimedia ni credenciales. La IA solo propone; no publica, responde, activa pauta ni gasta presupuesto.'));form.addEventListener('submit',async e=>{e.preventDefault();if(!settings.provider||!settings.model){opsToast('Configura provider y modelo primero');return}const selectedTask=task.select.value;if(selectedTask==='CAMPAIGN'&&!campaign.select.value){opsToast('Selecciona una campaña');return}if(selectedTask==='CREATIVE'&&!creative.select.value){opsToast('Selecciona un creativo');return}if(!confirm(`Se enviará contexto sanitizado a ${settings.provider} para generar una propuesta. ¿Continuar?`))return;generate.disabled=true;generate.textContent='Generando…';try{const company=wave51Company();const session=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/ai/generate`,{method:'POST',body:{task:selectedTask,campaign_id:campaign.select.value||null,creative_media_id:creative.select.value||null,instruction:instruction.value.trim()||null}});wave51AIState.lastSession=session;wave51AIState.sessions=[session,...wave51AIState.sessions.filter(row=>row.id!==session.id)].slice(0,10);opsToast('Propuesta generada');renderMarketingOps()}catch(err){opsToast(err.message)}finally{generate.disabled=false;generate.textContent='Generar con IA'}});root.append(form);wave51Result(root,wave51AIState.lastSession);if(wave51AIState.sessions.length){const history=opsEl('div','w51-history');for(const session of wave51AIState.sessions){const button=opsEl('button',session.id===wave51AIState.lastSession?.id?'active':'',`${session.task} · ${opsDate(session.created_at)}`);button.type='button';button.addEventListener('click',()=>{wave51AIState.lastSession=session;renderMarketingOps()});history.append(button)}root.append(opsEl('span','w51-kicker','HISTORIAL LOCAL'),history)}}

function wave51Panel(root){const section=opsEl('section','w51-ai'),head=opsEl('div','w51-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','AI COPILOT'),opsEl('h3','','Pensar mejor, no automatizar a ciegas'),opsEl('p','muted','Estrategia, briefs y variantes usando el contexto operativo real de la empresa.'));const current=wave51Provider(),badge=opsEl('span',`w51-badge ${current?.configured?'ok':''}`,current?`${current.name} · ${current.configured?'listo':'sin credencial'}`:'Configura provider');head.append(copy,badge);section.append(head);const grid=opsEl('div','w51-grid'),config=opsEl('div','w51-config'),work=opsEl('div','w51-work');config.append(opsEl('strong','','Provider & modelo'));wave51Config(config);work.append(opsEl('strong','','Copilot'));wave51Work(work);grid.append(config,work);section.append(grid);root.append(section)}

const wave51BaseRenderOpsHome=globalThis.renderOpsHome;
globalThis.renderOpsHome=function(root){wave51BaseRenderOpsHome(root);const company=wave51Company();if(!company)return;if(wave51AIState.companyId===company.id&&wave51AIState.settings){wave51Panel(root);return}const loading=opsEl('section','w51-ai');loading.append(opsEl('div','w51-empty','Cargando AI Copilot…'));root.append(loading);wave51Load(true).then(()=>{if(marketingOpsState.view==='home')renderMarketingOps()}).catch(err=>opsToast(err.message))};

const wave51BaseRefreshMarketingOps=globalThis.refreshMarketingOps;
globalThis.refreshMarketingOps=async function(force=false){const result=await wave51BaseRefreshMarketingOps(force);if(force){wave51AIState.companyId=null;wave51AIState.settings=null;wave51AIState.sessions=[];wave51AIState.lastSession=null}return result};

wave51Styles();if(marketingOpsState.view==='home')renderMarketingOps();
