const state={apps:[],projects:[],current:null,timeline:[]};
const $=s=>document.querySelector(s);
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node};
async function api(path,options={}){const init={...options,headers:{'Content-Type':'application/json',...(options.headers||{})}};if(init.body&&typeof init.body!=='string')init.body=JSON.stringify(init.body);const response=await fetch(path,init);let data=null;try{data=await response.json()}catch{data={error:`HTTP ${response.status}`}}if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.add('hidden'),3200)}
function fmtTime(value){try{return new Date(value).toLocaleString()}catch{return value||''}}
async function bootstrap(){try{const [health,apps,projects]=await Promise.all([api('/api/health'),api('/api/apps'),api('/api/projects')]);$('#health-dot').classList.add('ok');$('#health-text').textContent=`${health.version} · local`;state.apps=apps;state.projects=projects;renderApps();renderProjects();fillHandoffApps()}catch(err){$('#health-dot').classList.add('bad');$('#health-text').textContent='Sin conexión';toast(err.message)}}
function renderApps(){const root=$('#app-list');root.replaceChildren();for(const app of state.apps){const item=el('div','app-item');item.append(el('strong','',app.name),el('span','',app.service));root.append(item)}}
function renderProjects(){const root=$('#project-list');root.replaceChildren();if(!state.projects.length){root.append(el('p','muted','Todavía no hay proyectos.'));return}for(const project of state.projects){const item=el('div',`project-item${state.current?.project?.id===project.id?' active':''}`);item.dataset.projectId=project.id;item.append(el('strong','',project.name),el('span','',fmtTime(project.created_at)));item.addEventListener('click',()=>selectProject(project.id));root.append(item)}}
function fillHandoffApps(){const select=$('#handoff-app');select.replaceChildren();for(const app of state.apps){if(app.id==='05-editor-video-ia')continue;const option=el('option','',app.name);option.value=app.id;select.append(option)}}
async function refreshProjects(){state.projects=await api('/api/projects');renderProjects()}
async function selectProject(id){state.current=await api(`/api/projects/${id}`);$('#empty-state').classList.add('hidden');$('#project-view').classList.remove('hidden');renderProjects();renderProject();await refreshTimeline()}
function renderProject(){const current=state.current;if(!current)return;$('#active-project-name').textContent=current.project.name;$('#active-project-meta').textContent=`${current.project.id} · creado ${fmtTime(current.project.created_at)}`;$('#asset-count').textContent=current.assets.length;$('#clip-count').textContent=current.editor.clips.length;$('#handoff-count').textContent=current.handoffs.length;$('#aspect-badge').textContent=current.editor.aspect_ratio;$('#aspect-select').value=current.editor.aspect_ratio;renderAssets();renderTimeline();renderHandoffs()}
function renderAssets(){const root=$('#asset-list');const select=$('#clip-asset');root.replaceChildren();select.replaceChildren();const first=el('option','','Selecciona asset');first.value='';select.append(first);for(const asset of state.current.assets){const item=el('div','asset-item');const copy=el('div','asset-copy');copy.append(el('strong','',asset.name),el('span','',`${asset.kind} · ${asset.id}`));const del=el('button','','Eliminar');del.type='button';del.addEventListener('click',async()=>{try{await api(`/api/projects/${state.current.project.id}/assets/${asset.id}`,{method:'DELETE'});toast('Asset eliminado');await selectProject(state.current.project.id)}catch(err){toast(err.message)}});item.append(copy,del);root.append(item);const option=el('option','',asset.name);option.value=asset.id;select.append(option)}if(!state.current.assets.length)root.append(el('p','muted','Importa un archivo para comenzar.'))}
function renderTimeline(){const root=$('#timeline');root.replaceChildren();for(const clip of state.current.editor.clips){const row=el('div','clip-row');const main=el('div','clip-main');main.append(el('strong','',`Track ${clip.track} · ${clip.asset_id}`),el('p','',`${clip.start.toFixed(1)}s → ${clip.end.toFixed(1)}s · ${(clip.end-clip.start).toFixed(1)}s${clip.locked?' · bloqueado':''}`));const actions=el('div','clip-actions');const split=el('input');split.type='number';split.step='0.1';split.min=String(clip.start+.1);split.max=String(clip.end-.1);split.value=String(((clip.start+clip.end)/2).toFixed(1));const splitBtn=el('button','','Split');splitBtn.type='button';splitBtn.disabled=clip.locked;splitBtn.addEventListener('click',()=>editorAction({action:'split',clip_id:clip.id,at:Number(split.value)}));const lockBtn=el('button','',clip.locked?'Unlock':'Lock');lockBtn.type='button';lockBtn.addEventListener('click',()=>editorAction({action:'lock',clip_id:clip.id,value:!clip.locked}));const del=el('button','','×');del.type='button';del.disabled=clip.locked;del.addEventListener('click',()=>editorAction({action:'delete_clip',clip_id:clip.id}));actions.append(split,splitBtn,lockBtn,del);row.append(main,actions);root.append(row)}if(!state.current.editor.clips.length)root.append(el('p','muted','El timeline está vacío.'))}
function renderHandoffs(){const root=$('#handoff-list');root.replaceChildren();for(const handoff of [...state.current.handoffs].reverse()){const item=el('div','handoff-item');item.append(el('strong','',`${handoff.from_app} → ${handoff.to_app}`),el('p','',handoff.summary||'Sin resumen'),el('span','',fmtTime(handoff.created_at)));root.append(item)}if(!state.current.handoffs.length)root.append(el('p','muted','Aún no hay handoffs.'))}
async function editorAction(payload){if(!state.current)return;try{state.current.editor=await api(`/api/projects/${state.current.project.id}/editor/actions`,{method:'POST',body:payload});renderProject();await refreshTimeline()}catch(err){toast(err.message)}}
async function refreshTimeline(){state.timeline=await api('/api/timeline');const root=$('#unified-timeline');root.replaceChildren();for(const event of [...state.timeline].reverse().slice(0,80)){const item=el('div','event-item');item.append(el('time','',fmtTime(event.at)),el('div','',`${event.kind} · ${JSON.stringify(event.payload)}`));root.append(item)}if(!state.timeline.length)root.append(el('p','muted','Sin eventos todavía.'))}
$('#create-project').addEventListener('submit',async event=>{event.preventDefault();try{const project=await api('/api/projects',{method:'POST',body:{name:$('#project-name').value}});$('#project-name').value='';await refreshProjects();await selectProject(project.id);toast('Proyecto creado y respaldado en el Workspace')}catch(err){toast(err.message)}});
$('#asset-form').addEventListener('submit',async event=>{event.preventDefault();if(!state.current)return;try{await api(`/api/projects/${state.current.project.id}/assets`,{method:'POST',body:{source_path:$('#asset-path').value,kind:$('#asset-kind').value}});$('#asset-path').value='';toast('Asset importado');await selectProject(state.current.project.id)}catch(err){toast(err.message)}});
$('#clip-form').addEventListener('submit',async event=>{event.preventDefault();await editorAction({action:'add_clip',asset_id:$('#clip-asset').value,start:Number($('#clip-start').value),end:Number($('#clip-end').value),track:Number($('#clip-track').value)})});
document.querySelectorAll('[data-editor-action]').forEach(button=>button.addEventListener('click',()=>editorAction({action:button.dataset.editorAction})));
$('#aspect-select').addEventListener('change',()=>editorAction({action:'aspect',value:$('#aspect-select').value}));
$('#handoff-form').addEventListener('submit',async event=>{event.preventDefault();if(!state.current)return;try{await api(`/api/projects/${state.current.project.id}/handoffs`,{method:'POST',body:{from_app:'05-editor-video-ia',to_app:$('#handoff-app').value,summary:$('#handoff-summary').value}});$('#handoff-summary').value='';toast('Handoff registrado');await selectProject(state.current.project.id)}catch(err){toast(err.message)}});
$('#clipper-run').addEventListener('click',async()=>{try{const segments=$('#clipper-input').value.split('\n').filter(Boolean).map(line=>{const [start,end,...text]=line.split('|');return{start:Number(start),end:Number(end),text:text.join('|').trim()}});const results=await api('/api/clipper/select',{method:'POST',body:{segments,target_count:Number($('#clipper-count').value),min_duration:Number($('#clipper-min').value),max_duration:Number($('#clipper-max').value)}});const root=$('#clipper-results');root.replaceChildren();for(const clip of results){const item=el('div','result-item');item.append(el('strong','',`${clip.start.toFixed(1)}–${clip.end.toFixed(1)}s · score ${clip.score}`),el('p','',clip.text));root.append(item)}if(!results.length)root.append(el('p','muted','No hubo candidatos con esos límites.'))}catch(err){toast(err.message)}});
$('#refresh-timeline').addEventListener('click',refreshTimeline);
bootstrap();
