const audienceState={companyId:null,rows:[],contacts:[],selectedId:null,loading:false,loaded:false,lastImport:null};

function audienceEnsureStyles(){
  if(document.querySelector('#audience-wave36-style'))return;
  const style=document.createElement('style');style.id='audience-wave36-style';style.textContent=`
  .audience-layout{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(420px,1.5fr);gap:12px}.audience-list{display:grid;gap:8px}.audience-card{border:1px solid #dedbd2;border-radius:12px;padding:11px;background:#fff;display:grid;gap:6px;cursor:pointer}.audience-card.active{outline:2px solid #171717}.audience-card-head{display:flex;justify-content:space-between;gap:8px}.audience-counts{display:flex;gap:8px;flex-wrap:wrap}.audience-count{font-size:9px;color:#666159}.audience-form{display:grid;gap:9px}.audience-multiselect{min-height:180px}.audience-actions{display:flex;gap:8px;flex-wrap:wrap}.audience-import{display:grid;grid-template-columns:minmax(240px,1fr) 190px auto;gap:8px;align-items:end}.audience-import-report{margin-top:8px;padding:9px;border-radius:9px;background:#f4f2ed;font-size:10px}.audience-note{padding:9px;border:1px solid #dedbd2;border-radius:9px;background:#f5f2eb;font-size:10px}.audience-campaign-picker{display:grid;gap:4px;padding:9px;border:1px solid #dedbd2;border-radius:9px;background:#faf9f6}.audience-campaign-picker small{color:#77736b}
  @media(max-width:900px){.audience-layout,.audience-import{grid-template-columns:1fr}}
  `;document.head.append(style);
}

function audienceCompany(){return typeof opsSelectedCompany==='function'?opsSelectedCompany():null}
function audienceEnsureNav(){
  const nav=document.querySelector('.marketing-ops-nav');if(!nav||nav.querySelector('[data-ops-view="audiences"]'))return;
  const button=opsEl('button','','Audiencias');button.type='button';button.dataset.opsView='audiences';button.innerHTML='Audiencias <small>W36</small>';button.addEventListener('click',()=>opsShowView('audiences'));
  const crm=nav.querySelector('[data-ops-view="crm"]');if(crm)nav.insertBefore(button,crm.nextSibling);else nav.append(button)
}

async function audienceRefresh(force=false){
  const company=audienceCompany(),companyId=company?.id||null;
  if(!companyId){audienceState.companyId=null;audienceState.rows=[];audienceState.contacts=[];audienceState.loaded=true;return}
  if(audienceState.loading)return;
  if(!force&&audienceState.loaded&&audienceState.companyId===companyId)return;
  audienceState.loading=true;audienceState.companyId=companyId;
  try{
    const encoded=encodeURIComponent(companyId);const [rows,contacts]=await Promise.all([opsApi(`/api/companies/${encoded}/audiences`),opsApi(`/api/companies/${encoded}/contacts`)]);
    audienceState.rows=rows||[];audienceState.contacts=contacts||[];audienceState.loaded=true;
    if(audienceState.selectedId&&!audienceState.rows.some(row=>row.id===audienceState.selectedId))audienceState.selectedId=null
  }catch(err){opsToast(err.message)}finally{audienceState.loading=false}
}

function audienceCard(row){const card=opsEl('article',`audience-card ${row.id===audienceState.selectedId?'active':''}`),head=opsEl('div','audience-card-head'),left=opsEl('div','');left.append(opsEl('strong','',row.name),opsEl('p','muted',row.description||'Sin descripción'));head.append(left,opsEl('span','marketing-ops-badge',row.member_count||0));card.append(head);const counts=opsEl('div','audience-counts');counts.append(opsEl('span','audience-count',`${row.email_reachable||0} con email`),opsEl('span','audience-count',`${row.whatsapp_reachable||0} con WhatsApp/teléfono`));card.append(counts);card.addEventListener('click',()=>{audienceState.selectedId=row.id;audienceRenderCurrent()});return card}

function audienceSelectContacts(select,selectedIds){const selected=new Set(selectedIds||[]);select.replaceChildren();audienceState.contacts.forEach(contact=>{const details=[contact.organization,contact.email,contact.whatsapp||contact.phone].filter(Boolean).join(' · ');const option=opsEl('option','',`${contact.name}${details?` · ${details}`:''}`);option.value=contact.id;option.selected=selected.has(contact.id);select.append(option)})}
function audienceSelected(select){return [...select.selectedOptions].map(option=>option.value).filter(Boolean)}

function audienceEditor(root,row){
  const company=audienceCompany(),section=opsEl('section','marketing-ops-section');const head=opsEl('div','marketing-ops-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow',row?'EDITAR AUDIENCIA':'NUEVA AUDIENCIA'),opsEl('h3','',row?row.name:'Lista reutilizable'));head.append(copy);if(row){const fresh=opsEl('button','','+ Nueva');fresh.type='button';fresh.addEventListener('click',()=>{audienceState.selectedId=null;audienceRenderCurrent()});head.append(fresh)}section.append(head);
  const form=opsEl('form','audience-form');const nameLabel=opsEl('label','','Nombre');const name=document.createElement('input');name.required=true;name.maxLength=180;name.value=row?.name||'';name.placeholder='Ej. Clientes café Antioquia';nameLabel.append(name);form.append(nameLabel);const descLabel=opsEl('label','','Descripción');const description=document.createElement('textarea');description.maxLength=2000;description.value=row?.description||'';description.placeholder='Quiénes son y para qué se usa esta audiencia';descLabel.append(description);form.append(descLabel);const contactsLabel=opsEl('label','','Contactos');const contacts=document.createElement('select');contacts.multiple=true;contacts.className='audience-multiselect';audienceSelectContacts(contacts,row?.contact_ids||[]);contactsLabel.append(contacts);form.append(contactsLabel);form.append(opsEl('div','audience-note','Las audiencias son listas locales reutilizables. No envían mensajes. Cuando se usan en una campaña, sus contactos se copian como snapshot.'));
  const actions=opsEl('div','audience-actions'),save=opsEl('button','primary',row?'Guardar cambios':'Crear audiencia');save.type='submit';actions.append(save);if(row){const remove=opsEl('button','','Eliminar audiencia');remove.type='button';remove.addEventListener('click',async()=>{if(!confirm(`Eliminar la audiencia “${row.name}”? Esto no borra contactos ni cambia campañas ya guardadas.`))return;try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/audiences/${encodeURIComponent(row.id)}`,{method:'DELETE'});audienceState.selectedId=null;opsToast('Audiencia eliminada');await Promise.all([audienceRefresh(true),refreshMarketingOps(true)]);audienceRenderCurrent()}catch(err){opsToast(err.message)}});actions.append(remove)}form.append(actions);
  form.addEventListener('submit',async event=>{event.preventDefault();const payload={name:name.value.trim(),description:description.value.trim()||null,contact_ids:audienceSelected(contacts)};save.disabled=true;try{let saved;if(row)saved=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/audiences/${encodeURIComponent(row.id)}`,{method:'PATCH',body:payload});else saved=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/audiences`,{method:'POST',body:payload});audienceState.selectedId=saved.id;opsToast(row?'Audiencia actualizada':'Audiencia creada');await Promise.all([audienceRefresh(true),refreshMarketingOps(true)]);audienceRenderCurrent()}catch(err){opsToast(err.message)}finally{save.disabled=false}});section.append(form);root.append(section)
}

async function audienceImportCsv(file,strategy){
  const company=audienceCompany();if(!company||!file)return null;const url=`/api/companies/${encodeURIComponent(company.id)}/contacts/import?strategy=${encodeURIComponent(strategy)}`;const response=await fetch(url,{method:'POST',headers:{'Content-Type':'text/csv; charset=utf-8'},body:file});let payload={};try{payload=await response.json()}catch(_err){}if(!response.ok)throw new Error(payload.error||`Import HTTP ${response.status}`);return payload
}

function audienceImportSection(root){
  const section=opsEl('section','marketing-ops-section');const head=opsEl('div','marketing-ops-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','IMPORTAR CONTACTOS'),opsEl('h3','','CSV → CRM'),opsEl('p','muted','Columnas aceptadas en español o inglés: nombre/name, empresa/organization, cargo/role, correo/email, teléfono/phone, WhatsApp, Instagram, origen/source, etiquetas/tags, notas/notes.'));head.append(copy);section.append(head);const form=opsEl('form','audience-import');const fileLabel=opsEl('label','','Archivo CSV');const file=document.createElement('input');file.type='file';file.accept='.csv,text/csv';file.required=true;fileLabel.append(file);const strategyLabel=opsEl('label','','Si ya existe');const strategy=document.createElement('select');[['skip','Omitir duplicado'],['update','Actualizar campos no vacíos']].forEach(([value,label])=>{const option=opsEl('option','',label);option.value=value;strategy.append(option)});strategyLabel.append(strategy);const submit=opsEl('button','primary','Importar');submit.type='submit';form.append(fileLabel,strategyLabel,submit);form.addEventListener('submit',async event=>{event.preventDefault();const selected=file.files?.[0];if(!selected)return;submit.disabled=true;submit.textContent='Importando…';try{audienceState.lastImport=await audienceImportCsv(selected,strategy.value);file.value='';opsToast('Importación procesada');if(globalThis.crmRefresh)await crmRefresh(true);await Promise.all([audienceRefresh(true),refreshMarketingOps(true)]);audienceRenderCurrent()}catch(err){opsToast(err.message)}finally{submit.disabled=false;submit.textContent='Importar'}});section.append(form);if(audienceState.lastImport){const r=audienceState.lastImport,report=opsEl('div','audience-import-report',`${r.rows} filas · ${r.created} creados · ${r.updated} actualizados · ${r.skipped} omitidos · ${r.error_count} errores`);if(r.errors?.length)report.append(opsEl('div','muted',r.errors.slice(0,5).map(item=>`Fila ${item.row}: ${item.error}`).join(' | ')));section.append(report)}root.append(section)
}

function audienceRenderCurrent(){
  if(marketingOpsState.view!=='audiences')return;audienceEnsureStyles();audienceEnsureNav();const root=document.querySelector('#marketing-ops-view');if(!root)return;root.replaceChildren();document.querySelector('#marketing-ops-eyebrow').textContent='AUDIENCIAS';document.querySelector('#marketing-ops-title').textContent='Audiencias CRM';document.querySelector('#marketing-ops-subtitle').textContent='Importa contactos y guarda listas reutilizables sin enviar nada automáticamente.';document.querySelectorAll('[data-ops-view]').forEach(button=>button.classList.toggle('active',button.dataset.opsView==='audiences'));const company=audienceCompany();if(!company){root.append(opsEmpty('Selecciona una empresa para administrar audiencias.'));return}if(!audienceState.loaded||audienceState.companyId!==company.id){root.append(opsEmpty('Cargando audiencias…'));audienceRefresh(true).then(audienceRenderCurrent);return}
  const dashboard=marketingOpsState.dashboard?.audiences||{},metrics=opsEl('div','marketing-ops-grid');metrics.append(opsMetric('AUDIENCIAS',dashboard.total||0,'listas guardadas'),opsMetric('CONTACTOS ÚNICOS',dashboard.unique_contacts||0,'en al menos una lista'),opsMetric('MEMBRESÍAS',dashboard.memberships||0,'asignaciones totales'),opsMetric('CRM',audienceState.contacts.length,'contactos disponibles'));root.append(metrics);audienceImportSection(root);const layout=opsEl('div','audience-layout'),left=opsEl('section','marketing-ops-section'),head=opsEl('div','marketing-ops-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','LISTAS'),opsEl('h3','',`Audiencias de ${company.name}`));const add=opsEl('button','','+ Nueva');add.type='button';add.addEventListener('click',()=>{audienceState.selectedId=null;audienceRenderCurrent()});head.append(copy,add);left.append(head);const list=opsEl('div','audience-list');audienceState.rows.forEach(row=>list.append(audienceCard(row)));if(!audienceState.rows.length)list.append(opsEl('div','campaign-empty','Crea una audiencia o importa contactos por CSV para empezar.'));left.append(list);layout.append(left);const right=opsEl('div','');audienceEditor(right,audienceState.rows.find(row=>row.id===audienceState.selectedId)||null);layout.append(right);root.append(layout)
}

const audienceBaseRender=globalThis.renderMarketingOps;
globalThis.renderMarketingOps=function(){audienceEnsureNav();if(marketingOpsState.view==='audiences'){audienceRenderCurrent();return}audienceBaseRender()};

const audienceBaseCampaignForm=globalThis.campaignForm;
if(typeof audienceBaseCampaignForm==='function')globalThis.campaignForm=function(root,row){audienceBaseCampaignForm(root,row);const form=root.querySelector('.campaign-form');if(!form)return;const crmSelect=[...form.querySelectorAll('select[multiple]')][0];if(!crmSelect)return;const picker=opsEl('label','audience-campaign-picker','Audiencia guardada (opcional)');const select=document.createElement('select');const blank=opsEl('option','','Elegir lista y copiar contactos…');blank.value='';select.append(blank);const fill=()=>{const current=select.value;select.replaceChildren(blank);audienceState.rows.forEach(item=>{const option=opsEl('option','',`${item.name} · ${item.member_count||0} contactos`);option.value=item.id;select.append(option)});if([...select.options].some(option=>option.value===current))select.value=current};fill();select.addEventListener('change',()=>{const saved=audienceState.rows.find(item=>item.id===select.value);if(!saved)return;const ids=new Set(saved.contact_ids||[]);[...crmSelect.options].forEach(option=>{option.selected=ids.has(option.value)});opsToast(`Audiencia “${saved.name}” copiada: ${ids.size} contactos. La campaña guardará un snapshot.`)});picker.append(select,opsEl('small','','La campaña guarda los contactos seleccionados, no una referencia viva a la audiencia.'));crmSelect.closest('label')?.insertAdjacentElement('beforebegin',picker);audienceRefresh(false).then(fill)};

audienceEnsureStyles();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',audienceEnsureNav,{once:true});else audienceEnsureNav();
