const wave54CaptureState={companyId:null,data:null,loading:false};

function wave54Styles(){
  if(document.querySelector('#wave54-capture-style'))return;
  const style=document.createElement('style');style.id='wave54-capture-style';style.textContent=`
  .w54-shell{display:grid;gap:12px}.w54-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end}.w54-grid{display:grid;grid-template-columns:repeat(4,minmax(145px,1fr));gap:8px}.w54-card{padding:12px;border:1px solid #dedbd2;border-radius:12px;background:#fff;display:grid;gap:5px}.w54-card strong{font-size:18px}.w54-card span{font-size:8px;color:#716d65}.w54-two{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px}.w54-section{padding:14px;border:1px solid #dedbd2;border-radius:13px;background:#fff;display:grid;gap:10px}.w54-note{padding:10px;border-radius:10px;background:#f4f1e9;font-size:9px;line-height:1.5}.w54-note.good{background:#e9f2e8;border:1px solid #bdd1bd}.w54-code{white-space:pre-wrap;word-break:break-word;background:#181817;color:#f5f2e9;padding:12px;border-radius:10px;font:9px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.w54-actions{display:flex;gap:7px;flex-wrap:wrap}.w54-chip{display:inline-flex;padding:3px 7px;border-radius:999px;background:#efede7;font-size:8px}.w54-table{display:grid;gap:5px}.w54-row{display:grid;grid-template-columns:minmax(125px,.8fr) minmax(125px,.8fr) minmax(120px,.7fr) minmax(110px,.6fr) minmax(110px,.6fr);gap:7px;padding:8px 0;border-bottom:1px solid #eeeae2;align-items:center;font-size:9px}.w54-row.header{font-weight:700;color:#68645d}.w54-muted{font-size:8px;color:#77736b}.w54-list{display:grid;gap:7px}.w54-field{display:grid;grid-template-columns:150px 1fr;gap:8px;padding:7px 0;border-bottom:1px solid #eeeae2;font-size:9px}.w54-field code{font-size:8px}.w54-field:last-child{border-bottom:0}
  @media(max-width:1050px){.w54-grid{grid-template-columns:repeat(2,1fr)}.w54-two{grid-template-columns:1fr}}@media(max-width:700px){.w54-grid{grid-template-columns:1fr}.w54-head{align-items:flex-start;flex-direction:column}.w54-row{grid-template-columns:1fr 1fr}.w54-row.header{display:none}.w54-row>*:nth-child(n+3){display:none}.w54-field{grid-template-columns:1fr}}
  `;document.head.append(style)
}
function wave54Company(){return typeof wave53Company==='function'?wave53Company():(typeof wave47Company==='function'?wave47Company():null)}
function wave54Num(value){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('es-CO').format(n):'—'}
function wave54EnsureNav(){const nav=document.querySelector('.marketing-ops-nav');if(!nav||nav.querySelector('[data-ops-view="capture-bridge"]'))return;const button=opsEl('button','','Capture Bridge');button.type='button';button.dataset.opsView='capture-bridge';button.innerHTML='Capture Bridge <small>W54</small>';button.addEventListener('click',()=>opsShowView('capture-bridge'));const attribution=nav.querySelector('[data-ops-view="attribution"]');if(attribution?.nextSibling)nav.insertBefore(button,attribution.nextSibling);else nav.append(button)}
async function wave54Load(force=false){const company=wave54Company();if(!company){wave54CaptureState.companyId=null;wave54CaptureState.data=null;return}if(wave54CaptureState.loading)return;if(!force&&wave54CaptureState.companyId===company.id&&wave54CaptureState.data)return;wave54CaptureState.loading=true;try{wave54CaptureState.data=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/attribution/capture-bridge`);wave54CaptureState.companyId=company.id}catch(err){wave54CaptureState.data=null;opsToast(err.message)}finally{wave54CaptureState.loading=false}}
function wave54Metric(title,value,copy){const card=opsEl('div','w54-card');card.append(opsEl('span','',title),opsEl('strong','',value),opsEl('span','',copy));return card}
function wave54Copy(text,label){if(!navigator.clipboard){opsToast('Portapapeles no disponible');return}navigator.clipboard.writeText(text).then(()=>opsToast(label)).catch(()=>opsToast('No se pudo copiar'))}
function wave54Install(root){const section=opsEl('section','w54-section');section.append(opsEl('p','eyebrow','BRIDGE PORTABLE'),opsEl('h3','','Instrumentación de formularios sin red'),opsEl('div','w54-note good','El script solo lee bm_tid/UTM de la URL, los conserva durante la sesión y los agrega como hidden fields a formularios. No hace fetch, XHR, beacon, submit ni llamadas a Meta.'));const tag='<script src="/assets/binario-first-party-capture-bridge.js" defer></script>';const code=opsEl('pre','w54-code',tag),actions=opsEl('div','w54-actions'),download=document.createElement('a');download.href='/first-party-capture-bridge.js';download.download='binario-first-party-capture-bridge.js';download.className='primary';download.textContent='Descargar JS portable';const copy=opsEl('button','','Copiar tag de instalación');copy.type='button';copy.addEventListener('click',()=>wave54Copy(tag,'Tag copiado'));actions.append(download,copy);section.append(code,actions,opsEl('div','w54-note','Hospeda ese archivo dentro de tu propio dominio y ajusta el src. El navegador externo nunca debe depender del localhost de BINARIO.'));root.append(section)}
function wave54Mapping(root){const section=opsEl('section','w54-section');section.append(opsEl('p','eyebrow','CONTRATO DE DATOS'),opsEl('h3','','Del formulario al CRM'));const fields=[['bm_tid','obligatorio; resuelve el tracking link canónico'],['utm_source / utm_medium','se validan contra el link; contradicciones se rechazan'],['utm_campaign / utm_id','se validan; no deciden la campaña por sí mismas'],['utm_content / utm_term','opcionales; si llegan deben coincidir'],['bm_client_captured_at','informativo; nunca ordena el crédito'],['bm_landing_url / bm_referrer_url','se reducen a hostname al persistir'],['bm_bridge_version','trazabilidad del bridge portable']];const list=opsEl('div','w54-list');for(const [name,copy] of fields){const row=opsEl('div','w54-field');row.append(opsEl('code','',name),opsEl('span','',copy));list.append(row)}section.append(list);const json=`{
  "name": "Lead",
  "email": "...",
  "attribution_capture": {
    "bm_tid": "<hidden bm_tid>",
    "utm_source": "<hidden utm_source>",
    "utm_medium": "<hidden utm_medium>",
    "utm_campaign": "<hidden utm_campaign>",
    "utm_id": "<hidden utm_id>",
    "client_captured_at": "<hidden bm_client_captured_at>",
    "landing_url": "<hidden bm_landing_url>",
    "referrer_url": "<hidden bm_referrer_url>",
    "bridge_version": "<hidden bm_bridge_version>"
  }
}`;section.append(opsEl('pre','w54-code',json));const copy=opsEl('button','','Copiar ejemplo CRM');copy.type='button';copy.addEventListener('click',()=>wave54Copy(json,'Ejemplo CRM copiado'));section.append(copy);root.append(section)}
function wave54Recent(root,data){const section=opsEl('section','w54-section');section.append(opsEl('p','eyebrow','EVIDENCIA RECIBIDA'),opsEl('h3','','Capturas first-party verificadas'));const table=opsEl('div','w54-table'),header=opsEl('div','w54-row header');['Origen','Canal UTM','CRM','Landing host','Recibido'].forEach(label=>header.append(opsEl('span','',label)));table.append(header);for(const row of data.captures||[]){const line=opsEl('div','w54-row');const crm=row.opportunity_id?`Opp · ${row.opportunity_id.slice(-6)}`:row.contact_id?`Contacto · ${row.contact_id.slice(-6)}`:'—';line.append(opsEl('span','',row.source),opsEl('span','',`${row.utm_source} / ${row.utm_medium}`),opsEl('span','',crm),opsEl('span','',row.landing_host||'—'),opsEl('span','',new Date(row.received_at).toLocaleString('es-CO')));table.append(line)}if(!(data.captures||[]).length)table.append(opsEmpty('Aún no han llegado capturas verificadas desde formularios o CRM.'));section.append(table);root.append(section)}
function wave54Render(){wave54EnsureNav();wave54Styles();const root=document.querySelector('#marketing-ops-view');if(!root)return;root.replaceChildren();document.querySelector('#marketing-ops-eyebrow').textContent='FIRST-PARTY';document.querySelector('#marketing-ops-title').textContent='Capture Bridge';document.querySelector('#marketing-ops-subtitle').textContent='Transporta bm_tid desde la landing hasta CRM y conviértelo en evidencia verificable, sin fabricar clics.';document.querySelectorAll('[data-ops-view]').forEach(button=>button.classList.toggle('active',button.dataset.opsView==='capture-bridge'));const company=wave54Company();if(!company){root.append(opsEmpty('Selecciona una empresa para configurar captura first-party.'));return}if(!wave54CaptureState.data||wave54CaptureState.companyId!==company.id){root.append(opsEmpty('Cargando bridge local…'));wave54Load(true).then(renderMarketingOps);return}const data=wave54CaptureState.data,s=data.summary||{},head=opsEl('div','w54-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','CAPTURE PIPELINE'),opsEl('h3','',`First-party capture · ${company.name}`),opsEl('p','muted','El servidor valida bm_tid y UTM antes de escribir atribución.'));head.append(copy,opsEl('span','w54-chip','Server receive time'));root.append(head);const grid=opsEl('div','w54-grid');grid.append(wave54Metric('CAPTURAS',wave54Num(s.capture_records||0),'evidencia durable'),wave54Metric('LINKS INSTRUMENTADOS',wave54Num(s.links_instrumented||0),'tracking links W53'),wave54Metric('LINKS CON CAPTURA',wave54Num(s.links_with_capture||0),'al menos un CRM capture'),wave54Metric('OPP CAPTURADAS',wave54Num(s.opportunity_captures||0),'con bm_tid verificable'));root.append(grid);const two=opsEl('div','w54-two'),left=opsEl('div','w54-shell'),right=opsEl('div','w54-shell');wave54Install(left);wave54Mapping(right);two.append(left,right);root.append(two);wave54Recent(root,data)}
const wave54BaseRenderMarketingOps=globalThis.renderMarketingOps;
globalThis.renderMarketingOps=function(){wave54EnsureNav();if(marketingOpsState.view==='capture-bridge'){wave54Render();return}wave54BaseRenderMarketingOps()};
wave54EnsureNav();wave54Styles();
