const contactabilityState={cache:new Map(),loading:new Set()};
const CONTACTABILITY_LABELS={UNKNOWN:'Sin decisión',OPTED_IN:'Autorizado',OPTED_OUT:'Excluido'};
const CONTACTABILITY_CHANNEL_LABELS={email:'Email',whatsapp:'WhatsApp'};

function contactabilityEnsureStyles(){
  if(document.querySelector('#contactability-wave37-style'))return;
  const style=document.createElement('style');style.id='contactability-wave37-style';style.textContent=`
  .contactability-panel{margin-top:10px;padding-top:10px;border-top:1px solid #d7d2c8}.contactability-panel-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start;margin-bottom:8px}.contactability-panel-head p{margin:2px 0 0}.contactability-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.contactability-channel{padding:10px;border:1px solid #ddd8ce;border-radius:10px;background:#fff;display:grid;gap:7px}.contactability-channel-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.contactability-channel-head strong{font-size:11px}.contactability-state{font-size:9px;padding:3px 7px;border-radius:999px;background:#efede7}.contactability-state.eligible{background:#e8eee9}.contactability-form{display:grid;gap:6px}.contactability-form .two{display:grid;grid-template-columns:1fr 1fr;gap:6px}.contactability-form label{font-size:9px;color:#6e6a62}.contactability-form input,.contactability-form select{font-size:10px}.contactability-actions{display:flex;gap:6px;flex-wrap:wrap}.contactability-note{font-size:9px;color:#77736b;line-height:1.4}.contactability-readiness{display:grid;gap:6px;margin-top:8px}.contactability-readiness-row{padding:8px;border:1px solid #dedbd2;border-radius:8px;background:#f8f6f1;font-size:10px}.contactability-audience-strip{margin-top:6px;display:flex;gap:6px;flex-wrap:wrap}.contactability-audience-strip span{font-size:9px;padding:3px 6px;border-radius:999px;background:#efede7}
  @media(max-width:760px){.contactability-grid,.contactability-form .two{grid-template-columns:1fr}}
  `;document.head.append(style)
}

function contactabilityCompany(){return typeof opsSelectedCompany==='function'?opsSelectedCompany():null}
function contactabilityLocalDate(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return '';const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function contactabilityNowLocal(){const date=new Date();const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function contactabilityCacheKey(companyId,contactId){return `${companyId}:${contactId}`}

async function contactabilityLoad(contactId,force=false){
  const company=contactabilityCompany();if(!company||!contactId)return null;const key=contactabilityCacheKey(company.id,contactId);if(!force&&contactabilityState.cache.has(key))return contactabilityState.cache.get(key);if(contactabilityState.loading.has(key))return null;contactabilityState.loading.add(key);try{const payload=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/contacts/${encodeURIComponent(contactId)}/contactability`);contactabilityState.cache.set(key,payload);return payload}catch(err){opsToast(err.message);return null}finally{contactabilityState.loading.delete(key)}
}

function contactabilityStatusOption(value,label,current){const option=opsEl('option','',label);option.value=value;option.selected=value===current;return option}

function contactabilityChannelNode(payload,channel){
  const row=payload.channels[channel],card=opsEl('section','contactability-channel'),head=opsEl('div','contactability-channel-head');head.append(opsEl('strong','',CONTACTABILITY_CHANNEL_LABELS[channel]||channel),opsEl('span',`contactability-state ${row.eligible?'eligible':''}`,row.eligible?'Elegible':CONTACTABILITY_LABELS[row.status]||row.status));card.append(head);
  const form=opsEl('form','contactability-form');const first=opsEl('div','two');const statusLabel=opsEl('label','','Estado');const status=document.createElement('select');status.append(contactabilityStatusOption('UNKNOWN','Sin decisión',row.status),contactabilityStatusOption('OPTED_IN','Autorizado / OPTED_IN',row.status),contactabilityStatusOption('OPTED_OUT','Excluido / OPTED_OUT',row.status));statusLabel.append(status);const sourceLabel=opsEl('label','','Fuente / evidencia');const source=document.createElement('input');source.maxLength=160;source.value=row.source||'';source.placeholder='Formulario, evento, solicitud…';sourceLabel.append(source);first.append(statusLabel,sourceLabel);form.append(first);
  const second=opsEl('div','two');const capturedLabel=opsEl('label','','Fecha de captura');const captured=document.createElement('input');captured.type='datetime-local';captured.value=contactabilityLocalDate(row.captured_at);capturedLabel.append(captured);const noteLabel=opsEl('label','','Nota');const note=document.createElement('input');note.maxLength=2000;note.value=row.note||'';note.placeholder='Contexto adicional';noteLabel.append(note);second.append(capturedLabel,noteLabel);form.append(second);
  const availability=row.has_destination?(row.eligible?'Destino disponible + estado autorizado':'Destino disponible; requiere OPTED_IN para ser elegible'):'No hay dato de destino en CRM';form.append(opsEl('div','contactability-note',availability));const actions=opsEl('div','contactability-actions'),save=opsEl('button','primary','Guardar estado');save.type='submit';const reset=opsEl('button','','Restablecer a UNKNOWN');reset.type='button';actions.append(save,reset);form.append(actions);
  status.addEventListener('change',()=>{if(status.value!=='UNKNOWN'&&!captured.value)captured.value=contactabilityNowLocal()});form.addEventListener('submit',async event=>{event.preventDefault();const company=contactabilityCompany();if(!company)return;const explicit=status.value!=='UNKNOWN';if(explicit&&!source.value.trim()){opsToast('Indica la fuente/evidencia del estado explícito');return}if(explicit&&!captured.value){opsToast('Indica la fecha de captura');return}const body={status:status.value,source:source.value.trim()||null,captured_at:captured.value?new Date(captured.value).toISOString():null,note:note.value.trim()||null};save.disabled=true;try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/contacts/${encodeURIComponent(payload.contact_id)}/contactability/${channel}`,{method:'PATCH',body});contactabilityState.cache.delete(contactabilityCacheKey(company.id,payload.contact_id));opsToast('Contactabilidad actualizada');await Promise.all([contactabilityLoad(payload.contact_id,true),refreshMarketingOps(true)]);if(globalThis.audienceRefresh)audienceState.loaded=false;crmRenderCurrent()}catch(err){opsToast(err.message)}finally{save.disabled=false}});reset.addEventListener('click',async()=>{const company=contactabilityCompany();if(!company)return;try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/contacts/${encodeURIComponent(payload.contact_id)}/contactability/${channel}`,{method:'DELETE'});contactabilityState.cache.delete(contactabilityCacheKey(company.id,payload.contact_id));opsToast('Estado restablecido a UNKNOWN');await Promise.all([contactabilityLoad(payload.contact_id,true),refreshMarketingOps(true)]);if(globalThis.audienceRefresh)audienceState.loaded=false;crmRenderCurrent()}catch(err){opsToast(err.message)}});card.append(form);return card
}

const contactabilityBaseCrmDetail=globalThis.crmRenderContactDetail;
if(typeof contactabilityBaseCrmDetail==='function')globalThis.crmRenderContactDetail=function(root){
  contactabilityBaseCrmDetail(root);const detail=crmState.contactDetail;if(!detail?.contact)return;const company=contactabilityCompany();if(!company)return;const contactId=detail.contact.id,key=contactabilityCacheKey(company.id,contactId),payload=contactabilityState.cache.get(key);const card=root.querySelector('.crm-detail');if(!card)return;const panel=opsEl('div','contactability-panel'),head=opsEl('div','contactability-panel-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','CONTACTABILIDAD'),opsEl('strong','','Estado por canal'),opsEl('p','muted','UNKNOWN no se interpreta como autorización. Sólo OPTED_IN será elegible para un futuro envío por ese canal.'));head.append(copy);panel.append(head);if(!payload){panel.append(opsEl('div','contactability-note','Cargando estados…'));card.append(panel);contactabilityLoad(contactId).then(()=>crmRenderCurrent());return}const grid=opsEl('div','contactability-grid');grid.append(contactabilityChannelNode(payload,'email'),contactabilityChannelNode(payload,'whatsapp'));panel.append(grid);card.append(panel)
};

const contactabilityBaseAudienceCard=globalThis.audienceCard;
if(typeof contactabilityBaseAudienceCard==='function')globalThis.audienceCard=function(row){const card=contactabilityBaseAudienceCard(row),strip=opsEl('div','contactability-audience-strip');for(const channel of ['email','whatsapp']){const data=row.contactability?.[channel]||{};strip.append(opsEl('span','',`${CONTACTABILITY_CHANNEL_LABELS[channel]}: ${data.eligible||0} elegibles · ${data.unknown||0} sin decisión · ${data.opted_out||0} excluidos`))}card.append(strip);return card};

const contactabilityBaseCampaignReadiness=globalThis.campaignReadinessNode;
if(typeof contactabilityBaseCampaignReadiness==='function')globalThis.campaignReadinessNode=function(row){const node=contactabilityBaseCampaignReadiness(row),extra=opsEl('div','contactability-readiness');for(const channel of ['email','whatsapp']){if(!(row.channels||[]).includes(channel))continue;const data=row.readiness?.[channel]||{};extra.append(opsEl('div','contactability-readiness-row',`${CONTACTABILITY_CHANNEL_LABELS[channel]} · ${data.eligible||0} elegibles · ${data.unknown||0} sin decisión · ${data.opted_out||0} excluidos · ${data.has_destination||0} con destino. Gate futuro: OPTED_IN.`))}if(extra.childElementCount)node.append(extra);return node};

const contactabilityBaseHome=globalThis.renderOpsHome;
if(typeof contactabilityBaseHome==='function')globalThis.renderOpsHome=function(root){contactabilityBaseHome(root);const channels=marketingOpsState.dashboard?.contactability?.channels||{},email=channels.email||{},wa=channels.whatsapp||{};const section=opsEl('section','marketing-ops-section'),head=opsEl('div','marketing-ops-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','CONTACTABILIDAD'),opsEl('h3','','Elegibilidad futura por canal'),opsEl('p','muted','Estado operativo actual; no ejecuta envíos. UNKNOWN y OPTED_OUT permanecen suprimidos.'));head.append(copy);section.append(head);const grid=opsEl('div','marketing-ops-grid');grid.append(opsMetric('EMAIL ELEGIBLE',email.eligible||0,`${email.unknown||0} sin decisión`),opsMetric('EMAIL EXCLUIDO',email.opted_out||0,'OPTED_OUT'),opsMetric('WHATSAPP ELEGIBLE',wa.eligible||0,`${wa.unknown||0} sin decisión`),opsMetric('WHATSAPP EXCLUIDO',wa.opted_out||0,'OPTED_OUT'));section.append(grid);root.append(section)};

contactabilityEnsureStyles();
