const crmCsvState={file:null,text:null,preview:null,busy:false};

function crmCsvEnsureStyles(){
  if(document.querySelector('#crm-csv-wave45-style'))return;
  const style=document.createElement('style');style.id='crm-csv-wave45-style';style.textContent=`
  .crm-csv-panel{display:grid;gap:10px;margin-bottom:12px;padding:12px;border:1px solid #dcd8cf;border-radius:12px;background:#faf9f6}.crm-csv-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-end}.crm-csv-actions{display:flex;gap:8px;align-items:flex-end;flex-wrap:wrap}.crm-csv-file{display:grid;gap:4px;min-width:240px}.crm-csv-summary{display:flex;gap:6px;flex-wrap:wrap}.crm-csv-summary span{padding:5px 8px;border-radius:999px;background:#ebe8e1;font-size:9px}.crm-csv-errors{font-size:10px;color:#6f6b64;display:grid;gap:3px}.crm-csv-help{font-size:10px;color:#6f6b64;line-height:1.45}.crm-csv-panel button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:700px){.crm-csv-head{align-items:flex-start;flex-direction:column}.crm-csv-file{min-width:100%}}
  `;document.head.append(style)
}
function crmCsvCompany(){return typeof opsSelectedCompany==='function'?opsSelectedCompany():null}
function crmCsvReset(){crmCsvState.text=null;crmCsvState.preview=null}
async function crmCsvRequest(companyId,action,text){const response=await fetch(`/api/companies/${encodeURIComponent(companyId)}/crm/contacts/${action}`,{method:'POST',headers:{'Content-Type':'text/csv; charset=utf-8','Accept':'application/json'},body:text});let payload={};try{payload=await response.json()}catch(_err){}if(!response.ok)throw new Error(payload.error||`CSV HTTP ${response.status}`);return payload}
async function crmCsvPreview(file,button){const company=crmCsvCompany();if(!company||!file)return;if(file.size>2000000){opsToast('El CSV supera el límite de 2 MB');return}crmCsvState.busy=true;button.disabled=true;button.textContent='Revisando…';try{const text=await file.text();const preview=await crmCsvRequest(company.id,'import-preview',text);crmCsvState.text=text;crmCsvState.preview=preview;opsToast(`CSV revisado: ${preview.valid} contactos nuevos posibles`);crmRenderCurrent()}catch(err){crmCsvReset();opsToast(err.message)}finally{crmCsvState.busy=false;button.disabled=false;button.textContent='Previsualizar'}}
async function crmCsvImport(button){const company=crmCsvCompany(),preview=crmCsvState.preview,text=crmCsvState.text;if(!company||!preview||!text||crmCsvState.busy)return;if(!preview.valid){opsToast('No hay contactos válidos nuevos para importar');return}crmCsvState.busy=true;button.disabled=true;button.textContent='Importando…';try{const result=await crmCsvRequest(company.id,'import',text);opsToast(`${result.created} contactos importados · ${result.duplicates} duplicados omitidos · ${result.invalid} inválidos`);crmCsvState.file=null;crmCsvReset();await crmRefresh(true);await refreshMarketingOps(false);crmRenderCurrent()}catch(err){opsToast(err.message)}finally{crmCsvState.busy=false;button.disabled=false;button.textContent='Importar contactos'}}
function crmCsvExport(){const company=crmCsvCompany();if(!company)return;const link=document.createElement('a');link.href=`/api/companies/${encodeURIComponent(company.id)}/crm/contacts/export`;link.download='';link.rel='noopener';document.body.append(link);link.click();link.remove()}
function crmCsvPanel(){crmCsvEnsureStyles();const company=crmCsvCompany(),panel=opsEl('section','crm-csv-panel');const head=opsEl('div','crm-csv-head');const copy=opsEl('div','');copy.append(opsEl('p','eyebrow','PORTABILIDAD CRM'),opsEl('strong','',company?`Contactos de ${company.name}`:'Selecciona una empresa'),opsEl('div','crm-csv-help','Importa desde Excel/CSV sin cargar contactos uno por uno. Primero se previsualiza; duplicados y filas inválidas se omiten.'));const exportButton=opsEl('button','','Exportar CSV');exportButton.type='button';exportButton.disabled=!company;exportButton.addEventListener('click',crmCsvExport);head.append(copy,exportButton);panel.append(head);if(!company)return panel;const actions=opsEl('div','crm-csv-actions');const fileLabel=opsEl('label','crm-csv-file','Archivo CSV');const file=document.createElement('input');file.type='file';file.accept='.csv,text/csv';fileLabel.append(file);const previewButton=opsEl('button','','Previsualizar');previewButton.type='button';previewButton.disabled=true;const importButton=opsEl('button','primary','Importar contactos');importButton.type='button';importButton.disabled=true;file.addEventListener('change',()=>{crmCsvState.file=file.files?.[0]||null;crmCsvReset();previewButton.disabled=!crmCsvState.file;importButton.disabled=true});previewButton.addEventListener('click',()=>crmCsvPreview(crmCsvState.file,previewButton));importButton.addEventListener('click',()=>crmCsvImport(importButton));actions.append(fileLabel,previewButton,importButton);panel.append(actions);if(crmCsvState.preview){const p=crmCsvState.preview,summary=opsEl('div','crm-csv-summary');summary.append(opsEl('span','',`${p.rows} filas`),opsEl('span','',`${p.valid} nuevas válidas`),opsEl('span','',`${p.duplicates} duplicadas`),opsEl('span','',`${p.invalid} inválidas`));panel.append(summary);importButton.disabled=p.valid<1;const errors=opsEl('div','crm-csv-errors');(p.errors||[]).slice(0,8).forEach(row=>errors.append(opsEl('span','',`Fila ${row.line}: ${row.error}`)));if((p.errors||[]).length)panel.append(errors)}panel.append(opsEl('div','crm-csv-help','Columnas aceptadas: nombre, empresa, cargo, email, teléfono, WhatsApp, Instagram, origen, etiquetas y notas. También se aceptan equivalentes en inglés. CSV máximo: 2 MB / 5.000 contactos.'));return panel}
const crmCsvBaseRenderContacts=crmRenderContacts;crmRenderContacts=function(root){root.append(crmCsvPanel());crmCsvBaseRenderContacts(root)};
const crmCsvBaseRefresh=crmRefresh;crmRefresh=async function(force=false){const before=crmState.companyId;await crmCsvBaseRefresh(force);if(before!==crmState.companyId){crmCsvState.file=null;crmCsvReset()}};
crmCsvEnsureStyles();if(marketingOpsState.view==='crm'&&crmState.tab==='contacts')crmRenderCurrent();