const crmState={companyId:null,summary:null,contacts:[],opportunities:[],activities:[],tab:'contacts',loading:false,loaded:false,contactDetail:null};
const crmStages=[['NEW','Nuevo'],['CONTACTED','Contactado'],['INTERESTED','Interesado'],['PROPOSAL','Propuesta'],['WON','Ganado'],['LOST','Perdido']];
const crmKinds=[['NOTE','Nota'],['CALL','Llamada'],['WHATSAPP','WhatsApp'],['EMAIL','Email'],['MEETING','Reunión'],['TASK','Tarea']];

function crmMoney(value,currency='COP'){if(value===null||value===undefined||value==='')return 'Sin valor';try{return new Intl.NumberFormat('es-CO',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value))}catch(_err){return `${value} ${currency}`}}
function crmStageLabel(value){return crmStages.find(row=>row[0]===value)?.[1]||value}
function crmContactName(id){return crmState.contacts.find(row=>row.id===id)?.name||'Sin contacto'}
function crmLocalIso(value){if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed.toISOString()}
function crmTags(value){return String(value||'').split(',').map(item=>item.trim()).filter(Boolean).slice(0,30)}

function crmEnsureStyles(){
  if(document.querySelector('#crm-wave32-style'))return;
  const style=document.createElement('style');style.id='crm-wave32-style';style.textContent=`
    .crm-tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.crm-tabs button.active{background:#171717;color:#fff}
    .crm-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.crm-metric{padding:12px;border:1px solid #e1ded5;border-radius:12px;background:#fff}.crm-metric strong{display:block;font-size:22px;margin-top:4px}.crm-metric span{font-size:10px;color:#77736b}
    .crm-split{display:grid;grid-template-columns:minmax(280px,.72fr) minmax(0,1.4fr);gap:12px}.crm-form{display:grid;gap:9px}.crm-form .two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.crm-form textarea{min-height:76px}
    .crm-list{display:grid;gap:7px}.crm-contact{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:11px;border:1px solid #e1ded5;border-radius:11px;background:#fff;cursor:pointer}.crm-contact:hover{border-color:#99958b}.crm-contact strong,.crm-contact span{display:block}.crm-contact span{font-size:10px;color:#77736b;margin-top:2px}.crm-contact-tags{display:flex;gap:4px;flex-wrap:wrap;margin-top:5px}.crm-tag{padding:3px 6px;border-radius:999px;background:#efede7;font-size:9px}
    .crm-detail{margin-bottom:10px;padding:12px;border:1px solid #cfcac0;border-radius:12px;background:#f4f2ed}.crm-detail-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:8px}.crm-detail-grid div{padding:8px;background:#fff;border-radius:9px}.crm-detail-grid span{display:block;font-size:9px;color:#77736b}.crm-detail-grid strong{display:block;margin-top:2px;font-size:11px;overflow-wrap:anywhere}
    .crm-pipeline{display:grid;grid-template-columns:repeat(6,minmax(190px,1fr));gap:8px;overflow-x:auto;padding-bottom:6px}.crm-column{min-height:220px;padding:9px;border:1px solid #dedbd2;border-radius:12px;background:#f5f3ee}.crm-column-head{display:flex;justify-content:space-between;gap:6px;align-items:center;margin-bottom:8px}.crm-column-head strong{font-size:10px;text-transform:uppercase}.crm-opportunity{padding:9px;margin-bottom:7px;border:1px solid #ddd9d0;border-radius:10px;background:#fff}.crm-opportunity strong{display:block}.crm-opportunity p{margin:3px 0;color:#706d66;font-size:10px}.crm-opportunity select{margin-top:7px;width:100%;font-size:10px}
    .crm-followup{display:grid;grid-template-columns:minmax(0,1.3fr) 150px auto;gap:10px;align-items:center;padding:10px;border:1px solid #e1ded5;border-radius:11px;background:#fff}.crm-followup.done{opacity:.55}.crm-followup strong,.crm-followup span{display:block}.crm-followup span{font-size:10px;color:#77736b}.crm-overdue{border-left:3px solid #171717}
    .crm-home-strip{margin-top:14px}.crm-home-strip .marketing-ops-list{grid-template-columns:repeat(2,minmax(0,1fr))}
    @media(max-width:1050px){.crm-split{grid-template-columns:1fr}.crm-metrics{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:700px){.crm-form .two,.crm-detail-grid{grid-template-columns:1fr}.crm-followup{grid-template-columns:1fr}.crm-home-strip .marketing-ops-list{grid-template-columns:1fr}}
  `;document.head.append(style);
}

async function crmRefresh(force=false){
  const company=typeof opsSelectedCompany==='function'?opsSelectedCompany():null;
  const companyId=company?.id||null;
  if(!companyId){crmState.companyId=null;crmState.summary=marketingOpsState.dashboard?.crm||null;crmState.contacts=[];crmState.opportunities=[];crmState.activities=[];crmState.loaded=true;return}
  if(crmState.loading)return;
  if(!force&&crmState.loaded&&crmState.companyId===companyId)return;
  crmState.loading=true;crmState.companyId=companyId;
  try{
    const encoded=encodeURIComponent(companyId);
    const [summary,contacts,opportunities,activities]=await Promise.all([
      opsApi(`/api/crm/summary?company_id=${encoded}`),
      opsApi(`/api/companies/${encoded}/contacts`),
      opsApi(`/api/companies/${encoded}/opportunities`),
      opsApi(`/api/companies/${encoded}/activities`),
    ]);
    crmState.summary=summary;crmState.contacts=contacts||[];crmState.opportunities=opportunities||[];crmState.activities=activities||[];crmState.loaded=true;
  }catch(err){opsToast(err.message)}finally{crmState.loading=false}
}

function crmMetric(title,value,detail){const node=opsEl('div','crm-metric');node.append(opsEl('span','',title),opsEl('strong','',value),opsEl('span','',detail));return node}
function crmMetrics(root){const s=crmState.summary||{};const metrics=opsEl('div','crm-metrics');metrics.append(crmMetric('CONTACTOS',s.contacts||0,'personas registradas'),crmMetric('OPORTUNIDADES',s.opportunities_open||0,'abiertas'),crmMetric('SEGUIMIENTOS',s.pending_activities||0,'pendientes'),crmMetric('VENCIDOS',s.overdue_activities||0,'requieren atención'));root.append(metrics)}

function crmTabs(root){const tabs=opsEl('div','crm-tabs');[['contacts','Contactos'],['pipeline','Pipeline'],['followups','Seguimientos']].forEach(([value,label])=>{const button=opsEl('button',crmState.tab===value?'active':'',label);button.type='button';button.addEventListener('click',()=>{crmState.tab=value;crmRenderCurrent()});tabs.append(button)});root.append(tabs)}
function crmRenderCurrent(){if(marketingOpsState.view!=='crm')return;const root=document.querySelector('#marketing-ops-view');if(root){root.replaceChildren();renderCrm(root)}}

function crmRenderContactDetail(root){
  const detail=crmState.contactDetail;if(!detail)return;
  const c=detail.contact;const card=opsEl('div','crm-detail');const head=opsEl('div','marketing-ops-section-head');const copy=opsEl('div','');copy.append(opsEl('p','eyebrow','FICHA DEL CONTACTO'),opsEl('h3','',c.name),opsEl('p','muted',[c.organization,c.role].filter(Boolean).join(' · ')||'Sin organización'));const close=opsEl('button','','Cerrar');close.type='button';close.addEventListener('click',()=>{crmState.contactDetail=null;crmRenderCurrent()});head.append(copy,close);card.append(head);
  const grid=opsEl('div','crm-detail-grid');[['Email',c.email||'—'],['WhatsApp',c.whatsapp||c.phone||'—'],['Instagram',c.instagram||'—'],['Origen',c.source||'—'],['Oportunidades',detail.opportunities?.length||0],['Actividades',detail.activities?.length||0]].forEach(([label,value])=>{const item=opsEl('div','');item.append(opsEl('span','',label),opsEl('strong','',value));grid.append(item)});card.append(grid);if(c.notes)card.append(opsEl('p','muted',c.notes));root.append(card)
}

async function crmOpenContact(contactId){const company=opsSelectedCompany();if(!company)return;try{crmState.contactDetail=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/contacts/${encodeURIComponent(contactId)}`);crmRenderCurrent()}catch(err){opsToast(err.message)}}

function crmRenderContacts(root){
  crmRenderContactDetail(root);const split=opsEl('div','crm-split');const create=opsEl('section','marketing-ops-section');create.append(opsEl('p','eyebrow','NUEVO CONTACTO'),opsEl('h3','','Agregar persona'));
  const form=opsEl('form','crm-form');form.innerHTML=`<label>Nombre<input name="name" required placeholder="Nombre completo"></label><div class="two"><label>Empresa / organización<input name="organization"></label><label>Cargo<input name="role"></label></div><div class="two"><label>Email<input name="email" type="email"></label><label>Teléfono<input name="phone"></label></div><div class="two"><label>WhatsApp<input name="whatsapp"></label><label>Instagram<input name="instagram" placeholder="@usuario"></label></div><div class="two"><label>Origen<input name="source" placeholder="Instagram, referido, feria…"></label><label>Etiquetas<input name="tags" placeholder="cliente, café, Medellín"></label></div><label>Notas<textarea name="notes"></textarea></label><button class="primary" type="submit">Guardar contacto</button>`;
  form.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(form),company=opsSelectedCompany();if(!company)return;const payload={name:data.get('name'),organization:data.get('organization'),role:data.get('role'),email:data.get('email'),phone:data.get('phone'),whatsapp:data.get('whatsapp'),instagram:data.get('instagram'),source:data.get('source'),tags:crmTags(data.get('tags')),notes:data.get('notes')};try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/contacts`,{method:'POST',body:payload});form.reset();opsToast('Contacto guardado');await crmRefresh(true);await refreshMarketingOps(false);crmRenderCurrent()}catch(err){opsToast(err.message)}});create.append(form);split.append(create);
  const listSection=opsEl('section','marketing-ops-section');const head=opsEl('div','marketing-ops-section-head');const copy=opsEl('div','');copy.append(opsEl('p','eyebrow','CONTACTOS'),opsEl('h3','',`${crmState.contacts.length} registrados`));head.append(copy);listSection.append(head);const list=opsEl('div','crm-list');crmState.contacts.forEach(c=>{const item=opsEl('div','crm-contact');const left=opsEl('div','');left.append(opsEl('strong','',c.name),opsEl('span','',[c.organization,c.role,c.email,c.whatsapp||c.phone].filter(Boolean).join(' · ')||'Sin datos adicionales'));if(c.tags?.length){const tags=opsEl('div','crm-contact-tags');c.tags.forEach(tag=>tags.append(opsEl('span','crm-tag',tag)));left.append(tags)}const arrow=opsEl('span','','Ver ficha →');item.append(left,arrow);item.addEventListener('click',()=>crmOpenContact(c.id));list.append(item)});if(!crmState.contacts.length)list.append(opsEmpty('Aún no hay contactos en esta empresa.'));listSection.append(list);split.append(listSection);root.append(split)
}

function crmContactOptions(select,blank='Sin contacto'){select.replaceChildren();const empty=opsEl('option','',blank);empty.value='';select.append(empty);crmState.contacts.forEach(c=>{const option=opsEl('option','',c.name);option.value=c.id;select.append(option)})}

function crmRenderPipeline(root){
  const create=opsEl('section','marketing-ops-section');const head=opsEl('div','marketing-ops-section-head');const copy=opsEl('div','');copy.append(opsEl('p','eyebrow','OPORTUNIDAD'),opsEl('h3','','Nueva oportunidad'));head.append(copy);create.append(head);const form=opsEl('form','crm-form');const row=opsEl('div','two');const titleLabel=opsEl('label','','Nombre');const title=document.createElement('input');title.required=true;title.placeholder='Ej. Venta fertilizante finca X';titleLabel.append(title);const contactLabel=opsEl('label','','Contacto');const contact=document.createElement('select');crmContactOptions(contact);contactLabel.append(contact);row.append(titleLabel,contactLabel);form.append(row);const row2=opsEl('div','two');const valueLabel=opsEl('label','','Valor estimado');const value=document.createElement('input');value.type='number';value.min='0';value.step='1';valueLabel.append(value);const actionLabel=opsEl('label','','Próxima acción');const action=document.createElement('input');action.placeholder='Enviar propuesta';actionLabel.append(action);row2.append(valueLabel,actionLabel);form.append(row2);const row3=opsEl('div','two');const dateLabel=opsEl('label','','Fecha próxima acción');const date=document.createElement('input');date.type='datetime-local';dateLabel.append(date);const notesLabel=opsEl('label','','Notas');const notes=document.createElement('input');notesLabel.append(notes);row3.append(dateLabel,notesLabel);form.append(row3);const submit=opsEl('button','primary','Crear oportunidad');submit.type='submit';form.append(submit);form.addEventListener('submit',async event=>{event.preventDefault();const company=opsSelectedCompany();if(!company)return;const payload={title:title.value,contact_id:contact.value||null,value:value.value||null,currency:'COP',stage:'NEW',next_action:action.value,next_action_at:crmLocalIso(date.value),notes:notes.value};try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/opportunities`,{method:'POST',body:payload});form.reset();opsToast('Oportunidad creada');await crmRefresh(true);await refreshMarketingOps(false);crmRenderCurrent()}catch(err){opsToast(err.message)}});create.append(form);root.append(create);
  const pipeline=opsEl('div','crm-pipeline');crmStages.forEach(([stage,label])=>{const rows=crmState.opportunities.filter(item=>item.stage===stage),col=opsEl('section','crm-column');const colHead=opsEl('div','crm-column-head');colHead.append(opsEl('strong','',label),opsEl('span','marketing-ops-badge',rows.length));col.append(colHead);rows.forEach(op=>{const card=opsEl('div','crm-opportunity');card.append(opsEl('strong','',op.title),opsEl('p','',crmContactName(op.contact_id)),opsEl('p','',crmMoney(op.value,op.currency)));if(op.next_action)card.append(opsEl('p','',`Siguiente: ${op.next_action}${op.next_action_at?` · ${opsDate(op.next_action_at)}`:''}`));const select=document.createElement('select');crmStages.forEach(([value,labelText])=>{const option=opsEl('option','',labelText);option.value=value;if(value===op.stage)option.selected=true;select.append(option)});select.addEventListener('change',async()=>{const company=opsSelectedCompany();try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/opportunities/${encodeURIComponent(op.id)}`,{method:'PATCH',body:{stage:select.value}});opsToast('Etapa actualizada');await crmRefresh(true);await refreshMarketingOps(false);crmRenderCurrent()}catch(err){opsToast(err.message)}});card.append(select);col.append(card)});pipeline.append(col)});root.append(pipeline)
}

function crmOpportunityOptions(select){select.replaceChildren();const empty=opsEl('option','','Sin oportunidad');empty.value='';select.append(empty);crmState.opportunities.filter(op=>!['WON','LOST'].includes(op.stage)).forEach(op=>{const option=opsEl('option','',op.title);option.value=op.id;select.append(option)})}
function crmIsOverdue(row){return !row.completed_at&&row.due_at&&new Date(row.due_at).getTime()<Date.now()}
function crmActivityKey(row){return `${row.completed_at?'9':'0'}|${row.due_at||row.created_at}`}

function crmRenderFollowups(root){
  const split=opsEl('div','crm-split');const create=opsEl('section','marketing-ops-section');create.append(opsEl('p','eyebrow','NUEVO SEGUIMIENTO'),opsEl('h3','','Registrar gestión / tarea'));const form=opsEl('form','crm-form');const row=opsEl('div','two');const contactLabel=opsEl('label','','Contacto');const contact=document.createElement('select');crmContactOptions(contact);contactLabel.append(contact);const opportunityLabel=opsEl('label','','Oportunidad');const opportunity=document.createElement('select');crmOpportunityOptions(opportunity);opportunityLabel.append(opportunity);row.append(contactLabel,opportunityLabel);form.append(row);const row2=opsEl('div','two');const kindLabel=opsEl('label','','Tipo');const kind=document.createElement('select');crmKinds.forEach(([value,label])=>{const option=opsEl('option','',label);option.value=value;kind.append(option)});kindLabel.append(kind);const dueLabel=opsEl('label','','Vence / programado');const due=document.createElement('input');due.type='datetime-local';dueLabel.append(due);row2.append(kindLabel,dueLabel);form.append(row2);const summaryLabel=opsEl('label','','Detalle');const summary=document.createElement('textarea');summary.required=true;summary.placeholder='Ej. Llamar para confirmar recepción de propuesta';summaryLabel.append(summary);form.append(summaryLabel);const note=opsEl('div','marketing-ops-note','Registrar “WhatsApp”, “Email” o “Llamada” guarda la gestión en el CRM; no envía mensajes automáticamente.');form.append(note);const submit=opsEl('button','primary','Guardar seguimiento');submit.type='submit';form.append(submit);form.addEventListener('submit',async event=>{event.preventDefault();const company=opsSelectedCompany();if(!company)return;if(!contact.value&&!opportunity.value){opsToast('Selecciona un contacto o una oportunidad');return}const payload={contact_id:contact.value||null,opportunity_id:opportunity.value||null,kind:kind.value,summary:summary.value,due_at:crmLocalIso(due.value)};try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/activities`,{method:'POST',body:payload});form.reset();crmContactOptions(contact);crmOpportunityOptions(opportunity);opsToast('Seguimiento guardado');await crmRefresh(true);await refreshMarketingOps(false);crmRenderCurrent()}catch(err){opsToast(err.message)}});create.append(form);split.append(create);
  const listSection=opsEl('section','marketing-ops-section');const head=opsEl('div','marketing-ops-section-head');const copy=opsEl('div','');copy.append(opsEl('p','eyebrow','AGENDA'),opsEl('h3','','Seguimientos'));head.append(copy);listSection.append(head);const list=opsEl('div','crm-list');const rows=[...crmState.activities].sort((a,b)=>crmActivityKey(a).localeCompare(crmActivityKey(b)));rows.forEach(activity=>{const item=opsEl('div',`crm-followup ${activity.completed_at?'done':''} ${crmIsOverdue(activity)?'crm-overdue':''}`);const copyBox=opsEl('div','');copyBox.append(opsEl('strong','',`${crmKinds.find(row=>row[0]===activity.kind)?.[1]||activity.kind} · ${activity.contact_id?crmContactName(activity.contact_id):'Oportunidad'}`),opsEl('span','',activity.summary));const when=opsEl('div','');when.append(opsEl('span','',activity.completed_at?'Completado':crmIsOverdue(activity)?'Vencido':'Pendiente'),opsEl('strong','',activity.due_at?opsDate(activity.due_at):'Sin fecha'));const action=activity.completed_at?opsEl('span','marketing-ops-badge','HECHO'):opsEl('button','','Completar');if(!activity.completed_at){action.type='button';action.addEventListener('click',async()=>{const company=opsSelectedCompany();try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/activities/${encodeURIComponent(activity.id)}/complete`,{method:'POST',body:{}});opsToast('Seguimiento completado');await crmRefresh(true);await refreshMarketingOps(false);crmRenderCurrent()}catch(err){opsToast(err.message)}})}item.append(copyBox,when,action);list.append(item)});if(!rows.length)list.append(opsEmpty('No hay seguimientos todavía.'));listSection.append(list);split.append(listSection);root.append(split)
}

function renderCrm(root){
  crmEnsureStyles();const company=opsSelectedCompany();crmMetrics(root);if(!company){root.append(opsEmpty('Selecciona una empresa en el filtro superior para trabajar contactos, oportunidades y seguimientos. El resumen mostrado incluye todas las empresas.'));return}crmTabs(root);if(!crmState.loaded||crmState.companyId!==company.id){root.append(opsEmpty('Cargando CRM…'));crmRefresh(true).then(crmRenderCurrent);return}if(crmState.tab==='pipeline')crmRenderPipeline(root);else if(crmState.tab==='followups')crmRenderFollowups(root);else crmRenderContacts(root)
}

const crmBaseRenderHome=globalThis.renderOpsHome;
if(typeof crmBaseRenderHome==='function')globalThis.renderOpsHome=function(root){crmBaseRenderHome(root);const s=marketingOpsState.dashboard?.crm;if(!s)return;const section=opsEl('section','marketing-ops-section crm-home-strip');const head=opsEl('div','marketing-ops-section-head');const copy=opsEl('div','');copy.append(opsEl('p','eyebrow','CRM'),opsEl('h3','','Relaciones comerciales'));const open=opsEl('button','','Abrir CRM');open.type='button';open.addEventListener('click',()=>opsShowView('crm'));head.append(copy,open);section.append(head);const list=opsEl('div','marketing-ops-list');list.append(crmMetric('OPORTUNIDADES',s.opportunities_open||0,'abiertas'),crmMetric('SEGUIMIENTOS VENCIDOS',s.overdue_activities||0,'requieren atención'));section.append(list);root.append(section)};

globalThis.renderOpsCrm=renderCrm;
const crmNav=document.querySelector('[data-ops-view="crm"]');crmNav?.querySelector('small')?.remove();
crmEnsureStyles();
if(marketingOpsState.view==='crm'){crmRefresh(true).then(crmRenderCurrent)}else if(marketingOpsState.view==='home'&&typeof renderMarketingOps==='function'){renderMarketingOps()}