const POST_W99_EXECUTION_RETURN_KEY='binario.marketing.execution-return.v1';
const postW99ExecutionReturnState={active:null,lastResult:null,checking:false};

function executionReturnCompany(){return typeof todayCompany==='function'?todayCompany():(typeof opsSelectedCompany==='function'?opsSelectedCompany():null)}
function executionReturnPrimitive(value){return value===null||value===undefined?null:String(value)}
function executionReturnDestination(row){const action=row?.action||{};return{view:executionReturnPrimitive(action.view),tab:executionReturnPrimitive(action.tab),entity_id:executionReturnPrimitive(action.entity_id),lead_id:executionReturnPrimitive(action.lead_id),contact_id:executionReturnPrimitive(action.contact_id),opportunity_id:executionReturnPrimitive(action.opportunity_id),campaign_id:executionReturnPrimitive(action.campaign_id),media_id:executionReturnPrimitive(action.media_id)}}
function executionReturnRead(){try{const raw=sessionStorage.getItem(POST_W99_EXECUTION_RETURN_KEY);if(!raw)return null;const value=JSON.parse(raw);if(!value||value.schema!==POST_W99_EXECUTION_RETURN_KEY||!value.company_id||!value.action_id||!value.destination?.view){sessionStorage.removeItem(POST_W99_EXECUTION_RETURN_KEY);return null}return value}catch(_err){try{sessionStorage.removeItem(POST_W99_EXECUTION_RETURN_KEY)}catch(_ignore){}return null}}
function executionReturnWrite(value){postW99ExecutionReturnState.active=value;try{sessionStorage.setItem(POST_W99_EXECUTION_RETURN_KEY,JSON.stringify(value))}catch(_err){}return value}
function executionReturnForget(){postW99ExecutionReturnState.active=null;try{sessionStorage.removeItem(POST_W99_EXECUTION_RETURN_KEY)}catch(_err){}document.querySelector('#post-w99-execution-return-ribbon')?.remove()}
function executionReturnCapture(row){const company=executionReturnCompany(),destination=executionReturnDestination(row);if(!company?.id||!row?.id||!destination.view)return null;const plan=postW99TodayState?.payload?.plan||[],position=plan.findIndex(item=>item.id===row.id);postW99ExecutionReturnState.lastResult=null;return executionReturnWrite({schema:POST_W99_EXECUTION_RETURN_KEY,company_id:company.id,action_id:String(row.id),title:String(row.title||'Acción del plan'),source:String(row.source||'OTHER'),urgency:String(row.urgency||'LOW'),sequence:Number(row.operator?.sequence||(position>=0?position+1:1)),planned_count:Number(postW99TodayState?.payload?.summary?.planned||plan.length||1),destination,opened_at:new Date().toISOString()})}

function executionReturnStyles(){if(document.querySelector('#post-w99-execution-return-style'))return;const style=document.createElement('style');style.id='post-w99-execution-return-style';style.textContent=`
.execution-return-ribbon{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:10020;width:min(920px,calc(100vw - 28px));background:#171717;color:#fff;border:1px solid #3b3935;border-radius:14px;box-shadow:0 18px 50px rgba(0,0,0,.22);padding:11px 13px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:center}.execution-return-copy{display:grid;gap:3px;min-width:0}.execution-return-copy small{font-size:7px;letter-spacing:.09em;opacity:.62}.execution-return-copy strong{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.execution-return-copy span{font-size:8px;opacity:.72}.execution-return-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.execution-return-actions button{background:#fff;color:#171717;border-color:#fff}.execution-return-actions button.execution-return-secondary{background:transparent;color:#fff;border-color:#5b5750}.execution-return-result{border:1px solid #d7d1c7;border-radius:12px;background:#f7f4ee;padding:11px 13px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.execution-return-result-copy{display:grid;gap:4px}.execution-return-result-copy strong{font-size:11px}.execution-return-result-copy p{font-size:8px;color:#706a61;margin:0;line-height:1.45}.execution-return-result-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.today-step.execution-return-highlight{outline:2px solid #171717;outline-offset:2px;background:#fff}.execution-return-suspended{opacity:.7}@media(max-width:760px){.execution-return-ribbon,.execution-return-result{grid-template-columns:1fr}.execution-return-actions,.execution-return-result-actions{justify-content:flex-start}.execution-return-ribbon{bottom:10px}}
`;document.head.append(style)}

function executionReturnInToday(){const legacy=document.querySelector('main.shell'),legacyVisible=legacy&&!legacy.classList.contains('marketing-ops-hidden');return !legacyVisible&&marketingOpsState?.view==='today-execution'}
function executionReturnCurrentMatches(context){const company=executionReturnCompany();return Boolean(company?.id&&company.id===context?.company_id)}
function executionReturnResumeDestination(context){if(!context?.destination?.view)return;if(!executionReturnCurrentMatches(context)){const exists=(marketingOpsState?.companies||[]).some(company=>company.id===context.company_id);if(!exists){executionReturnForget();opsToast('La empresa del recorrido ya no está disponible.');return}marketingOpsState.selectedCompanyId=context.company_id;if(typeof fillCompanyFilter==='function')fillCompanyFilter()}if(typeof actionCenterOpen==='function'){actionCenterOpen({action:context.destination});return}if(context.destination.view==='content'&&typeof opsShowLegacy==='function'){opsShowLegacy();return}if(typeof opsShowView==='function')opsShowView(context.destination.view)}
function executionReturnRenderRibbon(){executionReturnStyles();document.querySelector('#post-w99-execution-return-ribbon')?.remove();const context=postW99ExecutionReturnState.active||executionReturnRead();postW99ExecutionReturnState.active=context;if(!context||executionReturnInToday()||!executionReturnCurrentMatches(context))return;const ribbon=opsEl('aside','execution-return-ribbon');ribbon.id='post-w99-execution-return-ribbon';const copy=opsEl('div','execution-return-copy');copy.append(opsEl('small','','PLAN DE HOY · CONTEXTO DE EJECUCIÓN'),opsEl('strong','',context.title),opsEl('span','',`Acción ${context.sequence||'—'} de ${context.planned_count||'—'} · ${context.source||'—'} · ${context.urgency||'—'}`));const actions=opsEl('div','execution-return-actions');const resume=opsEl('button','execution-return-secondary','Continuar acción');resume.type='button';resume.addEventListener('click',()=>executionReturnResumeDestination(context));const back=opsEl('button','','Volver y releer plan');back.type='button';back.addEventListener('click',()=>executionReturnBackToToday(context));const close=opsEl('button','execution-return-secondary','Salir del recorrido');close.type='button';close.addEventListener('click',()=>{executionReturnForget();opsToast('Contexto de ejecución cerrado; no se modificó ninguna tarea.')});actions.append(resume,back,close);ribbon.append(copy,actions);document.body.append(ribbon)}

async function executionReturnBackToToday(context){if(postW99ExecutionReturnState.checking)return;postW99ExecutionReturnState.checking=true;try{const exists=(marketingOpsState?.companies||[]).some(company=>company.id===context.company_id);if(!exists){executionReturnForget();opsToast('La empresa del recorrido ya no está disponible.');return}marketingOpsState.selectedCompanyId=context.company_id;if(typeof fillCompanyFilter==='function')fillCompanyFilter();let actionPayload=null,todayPayload=null;if(typeof actionCenterLoad==='function')actionPayload=await actionCenterLoad(true);else actionPayload=await opsApi(`/api/companies/${encodeURIComponent(context.company_id)}/action-center`);if(typeof todayLoad==='function')todayPayload=await todayLoad(true);else todayPayload=await opsApi(`/api/companies/${encodeURIComponent(context.company_id)}/today-execution`);if(!actionPayload||!todayPayload)throw new Error('No fue posible releer el estado local');const queue=actionPayload.queue||[],plan=todayPayload.plan||[],canonicalIndex=queue.findIndex(row=>row.id===context.action_id),todayIndex=plan.findIndex(row=>row.id===context.action_id);let state='NO_LONGER_PENDING';if(todayIndex>=0)state='STILL_IN_TODAY';else if(canonicalIndex>=0)state='STILL_PENDING';const currentAction=todayIndex>=0?plan[todayIndex]:(canonicalIndex>=0?queue[canonicalIndex]:null),nextAction=todayPayload.primary_action||null;postW99ExecutionReturnState.lastResult={state,action_id:context.action_id,title:context.title,previous_sequence:context.sequence,canonical_position:canonicalIndex>=0?canonicalIndex+1:null,today_sequence:todayIndex>=0?Number(plan[todayIndex]?.operator?.sequence||todayIndex+1):null,current_action:currentAction,next_action:nextAction,checked_at:new Date().toISOString()};executionReturnForget();opsShowView('today-execution')}catch(err){opsToast(err?.message||'No fue posible releer el plan.');executionReturnRenderRibbon()}finally{postW99ExecutionReturnState.checking=false}}

function executionReturnResultCopy(result){if(result.state==='STILL_IN_TODAY')return{title:'La acción sigue pendiente en el plan',detail:`Action Center todavía la incluye. Ahora aparece como acción ${result.today_sequence||'—'} del foco diario; no se marcó como hecha.`};if(result.state==='STILL_PENDING')return{title:'La acción sigue pendiente fuera del foco de cinco',detail:`Continúa en Action Center${result.canonical_position?` en la posición ${result.canonical_position}`:''}. Today no la oculta por completitud: solo aplica el límite diario.`};return{title:'La acción ya no aparece en Action Center',detail:'El estado local fue releído y esa action ID ya no está en la cola canónica. Esto no se interpreta por sí solo como “completada”; continúa con la prioridad actual.'}}
function executionReturnRenderResult(){const result=postW99ExecutionReturnState.lastResult;if(marketingOpsState?.view!=='today-execution'||!result)return;const root=document.querySelector('#marketing-ops-view');if(!root)return;root.querySelector('#post-w99-execution-return-result')?.remove();const message=executionReturnResultCopy(result),card=opsEl('section','execution-return-result');card.id='post-w99-execution-return-result';const copy=opsEl('div','execution-return-result-copy');copy.append(opsEl('span','eyebrow','REGRESO AL PLAN'),opsEl('strong','',message.title),opsEl('p','',message.detail));const actions=opsEl('div','execution-return-result-actions'),candidate=result.state==='NO_LONGER_PENDING'?result.next_action:result.current_action;if(candidate){const open=opsEl('button','primary',result.state==='NO_LONGER_PENDING'?'Abrir siguiente prioridad':'Reabrir acción');open.type='button';open.addEventListener('click',()=>todayOpen(candidate));actions.append(open)}const dismiss=opsEl('button','','Cerrar mensaje');dismiss.type='button';dismiss.addEventListener('click',()=>{postW99ExecutionReturnState.lastResult=null;card.remove();document.querySelectorAll('.execution-return-highlight').forEach(node=>node.classList.remove('execution-return-highlight'))});actions.append(dismiss);card.append(copy,actions);const hero=root.querySelector('.today-hero');if(hero)hero.insertAdjacentElement('afterend',card);else root.prepend(card);const highlightId=result.state==='STILL_IN_TODAY'?result.action_id:(result.state==='NO_LONGER_PENDING'?result.next_action?.id:null);if(highlightId){for(const node of root.querySelectorAll('[data-today-action-id]')){if(node.dataset.todayActionId===String(highlightId)){node.classList.add('execution-return-highlight');break}}}}
function executionReturnAfterRender(){executionReturnRenderRibbon();executionReturnRenderResult()}

const postW99ExecutionReturnBaseTodayOpen=globalThis.todayOpen;if(typeof postW99ExecutionReturnBaseTodayOpen==='function'){globalThis.todayOpen=function(row){executionReturnCapture(row);const value=postW99ExecutionReturnBaseTodayOpen(row);queueMicrotask(executionReturnRenderRibbon);return value}}
const postW99ExecutionReturnBaseTodayStep=globalThis.todayStep;if(typeof postW99ExecutionReturnBaseTodayStep==='function'){globalThis.todayStep=function(row){const node=postW99ExecutionReturnBaseTodayStep(row);if(row?.id)node.dataset.todayActionId=String(row.id);return node}}
const postW99ExecutionReturnBaseRender=globalThis.renderMarketingOps;if(typeof postW99ExecutionReturnBaseRender==='function'){globalThis.renderMarketingOps=function(){const value=postW99ExecutionReturnBaseRender.apply(this,arguments);executionReturnAfterRender();return value}}
const postW99ExecutionReturnBaseLegacy=globalThis.opsShowLegacy;if(typeof postW99ExecutionReturnBaseLegacy==='function'){globalThis.opsShowLegacy=function(){const value=postW99ExecutionReturnBaseLegacy.apply(this,arguments);executionReturnRenderRibbon();return value}}
postW99ExecutionReturnState.active=executionReturnRead();executionReturnStyles();queueMicrotask(executionReturnAfterRender);window.addEventListener('pageshow',executionReturnAfterRender);
