const WAVE74_VIEWS=['home','campaigns','pauta','calendar','publish','video','content','crm','audiences','analytics','inbox','companies'];
const wave74AuditState={running:false,last:null};
function wave74Delay(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function wave74EnsureStyle(){if(document.querySelector('#wave74-audit-style'))return;const style=document.createElement('style');style.id='wave74-audit-style';style.textContent=`
.w74-audit-action{margin-left:7px}.w74-audit-action button{border:1px solid #d8d3ca;background:#fff;border-radius:7px;padding:7px 9px;cursor:pointer;font:inherit}.w74-panel{position:fixed;inset:6vh 6vw;z-index:10030;background:#fff;border:1px solid #d8d3ca;border-radius:16px;box-shadow:0 20px 70px rgba(0,0,0,.2);padding:18px;overflow:auto;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.w74-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.w74-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:14px}.w74-row{border:1px solid #e1ddd5;border-radius:10px;padding:10px;display:grid;gap:4px}.w74-row.pass{background:#edf6ef}.w74-row.fail{background:#fbefec}.w74-row strong{font-size:11px}.w74-row span,.w74-dead{font-size:9px;color:#6e6961}.w74-dead{padding-left:16px;margin:4px 0}.w74-summary{margin-top:12px;padding:10px;border-radius:10px;background:#f4f1eb;font-size:11px}@media(max-width:900px){.w74-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.w74-panel{inset:3vh 3vw}.w74-grid{grid-template-columns:1fr}}
`;document.head.append(style)}
function wave74InstallAction(){wave74EnsureStyle();const top=document.querySelector('.marketing-ops-top');if(!top||top.querySelector('.w74-audit-action'))return;const wrap=document.createElement('div');wrap.className='w74-audit-action';const button=document.createElement('button');button.type='button';button.textContent='Auditar controles';button.addEventListener('click',()=>wave74RunInteractionAudit());wrap.append(button);top.append(wrap)}
function wave74ScopeForView(view){if(view==='content')return document.querySelector('main.shell');return document.querySelector('#marketing-ops-view')}
async function wave74RenderView(view){if(view==='content'){if(typeof globalThis.opsShowLegacy!=='function')throw new Error('opsShowLegacy no disponible');globalThis.opsShowLegacy()}else{if(typeof globalThis.opsShowView!=='function')throw new Error('opsShowView no disponible');globalThis.opsShowView(view)}await wave74Delay(220);const scope=wave74ScopeForView(view);if(!scope)throw new Error('scope de vista no disponible');return scope}
function wave74Label(row){return row.id?`#${row.id}`:(row.text||row.name||`${row.tag}:${row.type||'control'}`)}
function wave74ShowReport(report){wave74EnsureStyle();document.querySelector('#wave74-panel')?.remove();const panel=document.createElement('section');panel.id='wave74-panel';panel.className='w74-panel';const head=document.createElement('div');head.className='w74-head';const copy=document.createElement('div');const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.textContent='WAVE 74 · INTERACTION INTEGRITY';const title=document.createElement('h3');title.textContent=report.ready?'Controles conectados':'Controles por revisar';const desc=document.createElement('p');desc.className='muted';desc.textContent='Auditoría local de handlers. No hace clic, no envía formularios y no activa proveedores.';copy.append(eyebrow,title,desc);const close=document.createElement('button');close.type='button';close.textContent='Cerrar';close.addEventListener('click',()=>panel.remove());head.append(copy,close);panel.append(head);const grid=document.createElement('div');grid.className='w74-grid';for(const row of report.views){const item=document.createElement('div');item.className=`w74-row ${row.unwired.length?'fail':'pass'}`;const strong=document.createElement('strong');strong.textContent=`${row.unwired.length?'×':'✓'} ${row.view}`;const stats=document.createElement('span');stats.textContent=`${row.wired} directos/form · ${row.delegated} delegados · ${row.disabled} deshabilitados · ${row.unwired.length} sin handler`;item.append(strong,stats);if(row.unwired.length){const list=document.createElement('ul');list.className='w74-dead';for(const dead of row.unwired.slice(0,12)){const li=document.createElement('li');li.textContent=`${wave74Label(dead)} · ${dead.tag}${dead.type?`/${dead.type}`:''}`;list.append(li)}item.append(list)}grid.append(item)}panel.append(grid);const summary=document.createElement('div');summary.className='w74-summary';summary.textContent=`${report.totalControls} controles visibles · ${report.totalUnwired} sin handler · ${report.ready?'PASS':'FAIL'} · empresa ${report.companyName||'—'}`;panel.append(summary);document.body.append(panel)}
async function wave74RunInteractionAudit(){if(wave74AuditState.running)return wave74AuditState.last;const probe=globalThis.wave74InteractionProbe;if(!probe)throw new Error('interaction probe no disponible');const company=typeof globalThis.opsSelectedCompany==='function'?globalThis.opsSelectedCompany():null;if(!company){const report={ready:false,companyName:null,totalControls:0,totalUnwired:WAVE74_VIEWS.length,views:WAVE74_VIEWS.map(view=>({view,wired:0,delegated:0,disabled:0,unwired:[{tag:'view',text:'Crea o selecciona una empresa'}]}))};wave74AuditState.last=report;wave74ShowReport(report);return report}
  wave74AuditState.running=true;const originalView=globalThis.marketingOpsState?.view||'home';const legacyWasVisible=!document.querySelector('main.shell')?.classList.contains('marketing-ops-hidden');const views=[];try{for(const view of WAVE74_VIEWS){try{const scope=await wave74RenderView(view);const result=probe.auditScope(scope);views.push({view,...result})}catch(err){views.push({view,total:0,wired:0,delegated:0,disabled:0,controls:[],unwired:[{tag:'view',text:String(err?.message||err)}]})}}}finally{if(legacyWasVisible&&typeof globalThis.opsShowLegacy==='function')globalThis.opsShowLegacy();else if(typeof globalThis.opsShowView==='function')globalThis.opsShowView(originalView);wave74AuditState.running=false;wave74InstallAction()}
  const totalControls=views.reduce((sum,row)=>sum+row.total,0),totalUnwired=views.reduce((sum,row)=>sum+row.unwired.length,0),report={ready:totalUnwired===0,companyName:company.name,companyId:company.id,totalControls,totalUnwired,views,checkedAt:new Date().toISOString(),safety:{programmaticClicks:false,submittedForms:false,externalProviderActivation:false,mutationRequestsIssuedByAudit:false}};wave74AuditState.last=report;wave74ShowReport(report);window.dispatchEvent(new CustomEvent('wave74-interaction-audit-complete',{detail:report}));return report}
globalThis.wave74RunInteractionAudit=wave74RunInteractionAudit;globalThis.wave74AuditState=wave74AuditState;window.addEventListener('wave73-entry-ready',()=>wave74InstallAction());window.addEventListener('marketing-ops-refreshed',()=>wave74InstallAction());if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(wave74InstallAction,0),{once:true});else setTimeout(wave74InstallAction,0);
