const wave52LearningState={companyId:null,data:null,loading:false,refreshing:false,view:'learning'};

function wave52Styles(){
  if(document.querySelector('#wave52-learning-style'))return;
  const style=document.createElement('style');style.id='wave52-learning-style';style.textContent=`
  .w52-shell{display:grid;gap:12px}.w52-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end}.w52-actions{display:flex;gap:7px;flex-wrap:wrap}.w52-tabs{display:flex;gap:6px;flex-wrap:wrap}.w52-tabs button.active{background:#171717;color:#fff}.w52-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:8px}.w52-card{padding:12px;border:1px solid #dedbd2;border-radius:12px;background:#fff;display:grid;gap:5px}.w52-card strong{font-size:17px}.w52-card span{font-size:8px;color:#716d65}.w52-two{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(320px,.8fr);gap:12px}.w52-section{padding:14px;border:1px solid #dedbd2;border-radius:13px;background:#fff;display:grid;gap:9px}.w52-section-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-end}.w52-note{padding:10px;border-radius:10px;background:#f4f1e9;font-size:9px;line-height:1.45}.w52-note.warn{background:#fff0df;border:1px solid #e7b87e}.w52-table{display:grid;gap:5px}.w52-row{display:grid;grid-template-columns:minmax(180px,1.2fr) repeat(5,minmax(75px,.45fr));gap:7px;align-items:center;padding:8px;border-bottom:1px solid #eeeae2;font-size:9px}.w52-row.header{font-weight:700;color:#68645d}.w52-row:last-child{border-bottom:0}.w52-row strong{font-size:10px}.w52-muted{font-size:8px;color:#77736b}.w52-chip{display:inline-flex;padding:3px 6px;border-radius:999px;background:#efede7;font-size:8px}.w52-chip.observed{background:#e5f0e6}.w52-leaders{display:grid;grid-template-columns:1fr 1fr;gap:7px}.w52-leader{border:1px solid #e1ddd5;border-radius:10px;padding:9px;display:grid;gap:4px}.w52-leader strong{font-size:10px}.w52-leader span{font-size:8px;color:#6c685f}.w52-decision-form{display:grid;gap:8px}.w52-decision-form .two{display:grid;grid-template-columns:1fr 1fr;gap:7px}.w52-decision-form label{display:grid;gap:4px;font-size:8px;color:#69655e}.w52-decision-list{display:grid;gap:6px}.w52-decision{border:1px solid #e2ded6;border-radius:9px;padding:9px;display:grid;gap:4px}.w52-decision-head{display:flex;justify-content:space-between;gap:8px}.w52-history{display:flex;gap:6px;overflow:auto}.w52-history span{white-space:nowrap;padding:5px 8px;border-radius:999px;background:#efede7;font-size:8px}.w52-empty{padding:14px;border:1px dashed #d5d0c6;border-radius:10px;color:#706c65;font-size:9px}
  @media(max-width:1050px){.w52-grid{grid-template-columns:repeat(2,1fr)}.w52-two{grid-template-columns:1fr}.w52-row{grid-template-columns:minmax(180px,1fr) repeat(3,minmax(70px,.4fr))}.w52-row>*:nth-child(5),.w52-row>*:nth-child(6){display:none}}@media(max-width:700px){.w52-grid,.w52-leaders,.w52-decision-form .two{grid-template-columns:1fr}.w52-head,.w52-section-head{align-items:flex-start;flex-direction:column}.w52-row{grid-template-columns:1fr 1fr}.w52-row.header{display:none}.w52-row>*:nth-child(n+3){display:none}}
  `;document.head.append(style)
}

function wave52Company(){return typeof wave47Company==='function'?wave47Company():(typeof opsSelectedCompany==='function'?opsSelectedCompany():null)}
function wave52Num(value,digits=1){const number=Number(value);if(!Number.isFinite(number))return'—';return new Intl.NumberFormat('es-CO',{maximumFractionDigits:digits}).format(number)}
function wave52Pct(value){return value===null||value===undefined?'—':`${wave52Num(value,2)}%`}
function wave52Money(value,currencies){if(value===null||value===undefined)return'—';const suffix=(currencies||[]).length===1?` ${(currencies||[])[0]}`:'';return `${wave52Num(value,2)}${suffix}`}
function wave52EntityName(kind,id){const rows=kind==='CAMPAIGN'?(wave52LearningState.data?.campaigns||[]):(wave52LearningState.data?.creatives||[]);const row=rows.find(item=>(kind==='CAMPAIGN'?item.id:item.media_id)===id);return row?(row.name||row.title||id):id}

async function wave52Load(force=false){const company=wave52Company();if(!company){wave52LearningState.companyId=null;wave52LearningState.data=null;return}if(wave52LearningState.loading)return;if(!force&&wave52LearningState.companyId===company.id&&wave52LearningState.data)return;wave52LearningState.loading=true;try{wave52LearningState.data=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/learning`);wave52LearningState.companyId=company.id}catch(err){wave52LearningState.data=null;opsToast(err.message)}finally{wave52LearningState.loading=false}}

async function wave52Refresh(){const company=wave52Company();if(!company||wave52LearningState.refreshing)return;if(!confirm('Binario consultará explícitamente Meta para leer métricas orgánicas y de pauta y guardará un snapshot sanitizado. No publicará, activará ni modificará nada. ¿Continuar?'))return;wave52LearningState.refreshing=true;renderMarketingOps();try{wave52LearningState.data=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/learning/refresh`,{method:'POST',body:{date_preset:'last_7d',social_limit:20,paid_limit:20}});opsToast('Resultados actualizados y snapshot guardado')}catch(err){opsToast(err.message)}finally{wave52LearningState.refreshing=false;renderMarketingOps()}}

function wave52Metric(title,value,copy){const card=opsEl('div','w52-card');card.append(opsEl('span','',title),opsEl('strong','',value),opsEl('span','',copy));return card}
function wave52MetricGrid(root,data){const snap=data.latest_snapshot||{},social=snap.social?.totals||{},paid=snap.paid_media?.totals||{},crm=snap.crm||data.crm_current||{},currencies=snap.paid_media?.currencies||[];const won=Object.values(crm.value_by_currency||{}).reduce((sum,row)=>sum+Number(row.won_count||0),0);const grid=opsEl('div','w52-grid');grid.append(wave52Metric('ALCANCE ORGÁNICO',wave52Num(social.reach||0),'snapshot observado'),wave52Metric('INTERACCIONES',wave52Num(social.total_interactions||0),'orgánico observado'),wave52Metric('CLICKS PAUTA',wave52Num(paid.clicks||0),`${wave52Num(paid.impressions||0)} impresiones`),wave52Metric('SPEND OBSERVADO',wave52Money(paid.spend||0,currencies),'sin conversión de moneda'),wave52Metric('OPORTUNIDADES GANADAS',wave52Num(won),'CRM empresa · no atribuido'),wave52Metric('SNAPSHOTS',wave52Num(data.history?.length||0),'evidencia histórica local'));root.append(grid)}

function wave52Leaders(root,data){const section=opsEl('section','w52-section'),head=opsEl('div','w52-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','SEÑALES'),opsEl('h3','','Qué está mostrando mejor señal'));head.append(copy);section.append(head);const leaders=opsEl('div','w52-leaders'),paid=data.leaders?.paid_ctr,organic=data.leaders?.organic_interaction_rate;const p=opsEl('div','w52-leader');p.append(opsEl('strong','','Mejor CTR observado'),opsEl('span','',paid?`${paid.title} · ${wave52Pct(paid.value)}`:'Aún no hay suficiente evidencia de pauta'));const o=opsEl('div','w52-leader');o.append(opsEl('strong','','Mejor interacción / alcance'),opsEl('span','',organic?`${organic.title} · ${wave52Pct(organic.value)}`:'Aún no hay suficiente evidencia orgánica'));leaders.append(p,o);section.append(leaders,opsEl('div','w52-note','Estas señales son comparaciones del snapshot observado, no recomendaciones automáticas de inversión. Una pieza “líder” puede necesitar más volumen, control de audiencia o validación comercial antes de escalar.'));root.append(section)}

function wave52Rows(root,data,kind){const isCampaign=kind==='campaign',rows=isCampaign?(data.campaigns||[]):(data.creatives||[]),section=opsEl('section','w52-section'),head=opsEl('div','w52-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow',isCampaign?'CAMPAIGN PERFORMANCE':'CREATIVE PERFORMANCE'),opsEl('h3','',isCampaign?'Campañas con evidencia':'Creativos con evidencia'));head.append(copy);section.append(head);if(!rows.length){section.append(opsEl('div','w52-empty',isCampaign?'Crea campañas y captura un snapshot para construir aprendizaje.':'Guarda briefs en Creative Studio y captura resultados para compararlos.'));root.append(section);return}const table=opsEl('div','w52-table'),header=opsEl('div','w52-row header');['Activo','Evidencia','Org. rate','Paid CTR','Clicks','Spend'].forEach(label=>header.append(opsEl('span','',label)));table.append(header);for(const row of rows){const metrics=row.metrics||{},line=opsEl('div','w52-row'),name=isCampaign?row.name:row.title;const nameBox=opsEl('div','');nameBox.append(opsEl('strong','',name||'Activo'),opsEl('div','w52-muted',isCampaign?`${row.objective} · ${row.status}`:`${row.purpose||'—'} · ${row.stage||'—'}`));const evidence=opsEl('span',`w52-chip ${row.evidence==='OBSERVED'?'observed':''}`,row.evidence==='OBSERVED'?'Observado':'Sin evidencia');const decision=row.latest_decision?.action?` · ${row.latest_decision.action}`:'';if(decision)evidence.textContent+=decision;line.append(nameBox,evidence,opsEl('span','',wave52Pct(metrics.organic_interaction_rate)),opsEl('span','',wave52Pct(metrics.paid_ctr)),opsEl('span','',wave52Num(metrics.clicks||0)),opsEl('span','',wave52Num(metrics.spend||0)));table.append(line)}section.append(table);root.append(section)}

function wave52DecisionForm(root,data){const section=opsEl('section','w52-section');section.append(opsEl('p','eyebrow','DECISIÓN HUMANA'),opsEl('h3','','Convertir evidencia en una decisión local'),opsEl('div','w52-note','Registrar una decisión documenta criterio y aprendizaje. SCALE, ITERATE, HOLD o RETIRE no cambia campañas, publicaciones ni Ads por sí mismo.'));const form=opsEl('form','w52-decision-form'),row=opsEl('div','two'),kindLabel=opsEl('label','','Tipo'),kind=document.createElement('select');[['CAMPAIGN','Campaña'],['CREATIVE','Creativo']].forEach(([v,l])=>{const o=opsEl('option','',l);o.value=v;kind.append(o)});kindLabel.append(kind);const entityLabel=opsEl('label','','Activo'),entity=document.createElement('select');entityLabel.append(entity);row.append(kindLabel,entityLabel);const actionLabel=opsEl('label','','Decisión'),action=document.createElement('select');[['SCALE','Escalar'],['ITERATE','Iterar'],['HOLD','Mantener'],['RETIRE','Retirar del plan']].forEach(([v,l])=>{const o=opsEl('option','',l);o.value=v;action.append(o)});actionLabel.append(action);const rationaleLabel=opsEl('label','','Razonamiento'),rationale=document.createElement('textarea');rationale.rows=3;rationale.required=true;rationale.placeholder='Qué evidencia soporta la decisión y qué deberíamos aprender…';rationaleLabel.append(rationale);form.append(row,actionLabel,rationaleLabel);const save=opsEl('button','primary','Registrar decisión local');save.type='submit';form.append(save);function fill(){entity.replaceChildren();const rows=kind.value==='CAMPAIGN'?(data.campaigns||[]):(data.creatives||[]);for(const item of rows){const o=opsEl('option','',item.name||item.title||item.id||item.media_id);o.value=kind.value==='CAMPAIGN'?item.id:item.media_id;entity.append(o)}entity.disabled=!rows.length;save.disabled=!rows.length}kind.addEventListener('change',fill);fill();form.addEventListener('submit',async e=>{e.preventDefault();if(!entity.value)return;save.disabled=true;try{const company=wave52Company();await opsApi(`/api/companies/${encodeURIComponent(company.id)}/learning/decisions`,{method:'POST',body:{entity_kind:kind.value,entity_id:entity.value,action:action.value,rationale:rationale.value.trim(),snapshot_id:data.latest_snapshot?.id||null}});rationale.value='';await wave52Load(true);opsToast('Decisión registrada sin ejecutar cambios remotos');renderMarketingOps()}catch(err){opsToast(err.message)}finally{save.disabled=false}});section.append(form);root.append(section)}

function wave52Decisions(root,data){const section=opsEl('section','w52-section'),head=opsEl('div','w52-section-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','MEMORIA DE APRENDIZAJE'),opsEl('h3','','Decisiones recientes'));head.append(copy);section.append(head);const list=opsEl('div','w52-decision-list');for(const row of (data.decisions||[]).slice(0,10)){const item=opsEl('div','w52-decision'),h=opsEl('div','w52-decision-head');h.append(opsEl('strong','',`${row.action} · ${wave52EntityName(row.entity_kind,row.entity_id)}`),opsEl('span','w52-chip',row.entity_kind));item.append(h,opsEl('div','w52-muted',row.rationale),opsEl('div','w52-muted',`${opsDate(row.created_at)}${row.snapshot_id?` · ${row.snapshot_id.slice(0,18)}…`:''}`));list.append(item)}if(!(data.decisions||[]).length)list.append(opsEl('div','w52-empty','Aún no has registrado decisiones basadas en resultados.'));section.append(list);root.append(section)}

function wave52History(root,data){if(!(data.history||[]).length)return;const section=opsEl('section','w52-section');section.append(opsEl('p','eyebrow','EVIDENCIA'),opsEl('h3','','Snapshots guardados'));const history=opsEl('div','w52-history');for(const row of data.history)history.append(opsEl('span','',`${row.date_preset} · ${opsDate(row.created_at)}`));section.append(history);root.append(section)}

function wave52Learning(root){const company=wave52Company();if(!company){root.append(opsEmpty('Selecciona una empresa para construir su learning loop.'));return}const data=wave52LearningState.data;if(!data){root.append(opsEmpty('Cargando Analytics & Learning Loop…'));wave52Load(true).then(renderMarketingOps);return}const latest=data.latest_snapshot;const head=opsEl('div','w52-head'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','ANALYTICS & LEARNING LOOP'),opsEl('h3','',`Aprendizaje · ${company.name}`),opsEl('p','muted','Une rendimiento orgánico, pauta, campañas, creativos y resultado CRM sin inventar atribución.'));const actions=opsEl('div','w52-actions'),refresh=opsEl('button','primary',wave52LearningState.refreshing?'Consultando Meta…':'Actualizar resultados desde Meta');refresh.type='button';refresh.disabled=wave52LearningState.refreshing;refresh.addEventListener('click',wave52Refresh);actions.append(refresh);head.append(copy,actions);root.append(head);if(!latest){root.append(opsEl('div','w52-note','Todavía no hay snapshot. Pulsa “Actualizar resultados desde Meta” para consultar explícitamente el readback disponible y guardar la primera línea de evidencia. El CRM se resume localmente y no se atribuye a campañas.'));wave52MetricGrid(root,data);wave52DecisionForm(root,data);return}root.append(opsEl('div','w52-note warn',`Snapshot ${latest.date_preset} · ${opsDate(latest.created_at)}. CRM→campaña: NO ATRIBUIDO. Las métricas se guardan como evidencia observada; Binario no interpreta una correlación como causalidad.`));wave52MetricGrid(root,data);wave52Leaders(root,data);const two=opsEl('div','w52-two'),left=opsEl('div','w52-shell'),right=opsEl('div','w52-shell');wave52Rows(left,data,'campaign');wave52Rows(left,data,'creative');wave52DecisionForm(right,data);wave52Decisions(right,data);two.append(left,right);root.append(two);wave52History(root,data)}

function wave52RenderAnalytics(){wave52Styles();const root=document.querySelector('#marketing-ops-view');if(!root)return;root.replaceChildren();document.querySelector('#marketing-ops-eyebrow').textContent='ANALÍTICA';document.querySelector('#marketing-ops-title').textContent='Analytics & Learning Loop';document.querySelector('#marketing-ops-subtitle').textContent='De resultados observados a decisiones documentadas, sin automatización ciega.';document.querySelectorAll('[data-ops-view]').forEach(button=>button.classList.toggle('active',button.dataset.opsView==='analytics'));const tabs=opsEl('div','w52-tabs'),learning=opsEl('button',wave52LearningState.view==='learning'?'active':'','Learning Loop'),legacy=opsEl('button',wave52LearningState.view==='social'?'active':'','Detalle social');learning.type=legacy.type='button';learning.addEventListener('click',()=>{wave52LearningState.view='learning';renderMarketingOps()});legacy.addEventListener('click',()=>{wave52LearningState.view='social';renderMarketingOps()});tabs.append(learning,legacy);root.append(tabs);if(wave52LearningState.view==='social'&&typeof wave52BaseAnalyticsRenderCurrent==='function'){wave52BaseAnalyticsRenderCurrent();return}wave52Learning(root)}

const wave52BaseAnalyticsRenderCurrent=globalThis.analyticsRenderCurrent;
const wave52BaseRenderMarketingOps=globalThis.renderMarketingOps;
globalThis.renderMarketingOps=function(){if(marketingOpsState.view==='analytics'){wave52RenderAnalytics();return}wave52BaseRenderMarketingOps()};

wave52Styles();
