const WAVE73_VIEWS=['home','campaigns','pauta','calendar','publish','video','content','crm','audiences','analytics','inbox','companies'];
const wave73JourneyState={running:false,last:null};

function wave73JourneyStyles(){if(document.querySelector('#wave73-journey-style'))return;const style=document.createElement('style');style.id='wave73-journey-style';style.textContent=`
.w73-journey-action{margin-left:7px}.w73-journey-action button{border:1px solid #d8d3ca;background:#fff;border-radius:7px;padding:7px 9px;cursor:pointer;font:inherit}.w73-journey-panel{position:fixed;inset:7vh 7vw;z-index:10020;background:#fff;border:1px solid #d8d3ca;border-radius:16px;box-shadow:0 20px 70px rgba(0,0,0,.18);padding:18px;overflow:auto;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.w73-journey-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.w73-journey-head h3{margin:3px 0}.w73-journey-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:14px}.w73-journey-row{border:1px solid #e1ddd5;border-radius:10px;padding:10px;display:grid;gap:4px}.w73-journey-row.pass{background:#edf6ef}.w73-journey-row.fail{background:#fbefec}.w73-journey-row strong{font-size:11px}.w73-journey-row span{font-size:9px;color:#6e6961}.w73-journey-summary{margin-top:12px;padding:10px;border-radius:10px;background:#f4f1eb;font-size:11px}@media(max-width:900px){.w73-journey-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.w73-journey-panel{inset:3vh 3vw}.w73-journey-grid{grid-template-columns:1fr}}
`;document.head.append(style)}
function wave73Delay(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function wave73InstallJourneyAction(){wave73JourneyStyles();const top=document.querySelector('.marketing-ops-top');if(!top||top.querySelector('.w73-journey-action'))return;const wrap=document.createElement('div');wrap.className='w73-journey-action';const button=document.createElement('button');button.type='button';button.textContent='Verificar interfaz';button.addEventListener('click',()=>wave73RunJourneyCheck());wrap.append(button);top.append(wrap)}
function wave73ShowJourney(report){wave73JourneyStyles();document.querySelector('#wave73-journey-panel')?.remove();const panel=document.createElement('section');panel.id='wave73-journey-panel';panel.className='w73-journey-panel';const head=document.createElement('div');head.className='w73-journey-head';const copy=document.createElement('div');const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.textContent='WAVE 73 · UI JOURNEY';const title=document.createElement('h3');title.textContent=report.ready?'Interfaz navegable':'Interfaz con bloqueos';const desc=document.createElement('p');desc.className='muted';desc.textContent='Prueba local de render y navegación. No envía formularios, no publica y no activa proveedores.';copy.append(eyebrow,title,desc);const close=document.createElement('button');close.type='button';close.textContent='Cerrar';close.addEventListener('click',()=>panel.remove());head.append(copy,close);panel.append(head);const grid=document.createElement('div');grid.className='w73-journey-grid';for(const row of report.views){const item=document.createElement('div');item.className=`w73-journey-row ${row.status.toLowerCase()}`;const strong=document.createElement('strong');strong.textContent=`${row.status==='PASS'?'✓':'×'} ${row.view}`;const detail=document.createElement('span');detail.textContent=row.detail;item.append(strong,detail);grid.append(item)}panel.append(grid);const summary=document.createElement('div');summary.className='w73-journey-summary';summary.textContent=`${report.pass}/${report.total} vistas PASS · empresa ${report.companyName||'—'} · ${report.ready?'recorrido completo':'revisar vistas fallidas'}`;panel.append(summary);document.body.append(panel)}
async function wave73InspectView(view){
  const errors=[];const onError=event=>errors.push(String(event?.error?.message||event?.message||'error de navegador'));window.addEventListener('error',onError);
  try{
    if(view==='content'){
      if(typeof globalThis.opsShowLegacy!=='function')throw new Error('opsShowLegacy no disponible');globalThis.opsShowLegacy();await wave73Delay(80);const legacy=document.querySelector('main.shell');if(!legacy||legacy.classList.contains('marketing-ops-hidden'))throw new Error('Workspace de contenido no visible');if(!document.querySelector('#create-project')||!document.querySelector('#app-list'))throw new Error('Controles base de contenido incompletos');
    }else{
      if(typeof globalThis.opsShowView!=='function')throw new Error('opsShowView no disponible');globalThis.opsShowView(view);await wave73Delay(180);const shell=document.querySelector('#marketing-ops-shell'),root=document.querySelector('#marketing-ops-view'),nav=document.querySelector(`[data-ops-view="${view}"]`);if(!shell||shell.classList.contains('marketing-ops-hidden'))throw new Error('shell empresarial no visible');if(!root||root.textContent.trim().length<3)throw new Error('vista sin contenido renderizado');if(!nav)throw new Error('navegación no declarada');if(!nav.classList.contains('active'))throw new Error('navegación no sincronizada');if(view==='companies'&&!root.querySelector('input[required]'))throw new Error('alta de empresa no disponible');if(view==='publish'&&!root.querySelector('form'))throw new Error('formulario de publicación no disponible');
    }
    if(errors.length)throw new Error(errors[0]);return {view,status:'PASS',detail:'Render, navegación y controles base disponibles'}
  }catch(err){return {view,status:'FAIL',detail:String(err?.message||err)}}finally{window.removeEventListener('error',onError)}
}
async function wave73RunJourneyCheck(){
  if(wave73JourneyState.running)return wave73JourneyState.last;const company=typeof globalThis.opsSelectedCompany==='function'?globalThis.opsSelectedCompany():null;if(!company){const report={ready:false,total:WAVE73_VIEWS.length,pass:0,companyName:null,views:WAVE73_VIEWS.map(view=>({view,status:'FAIL',detail:'Crea o selecciona una empresa antes de verificar'}))};wave73JourneyState.last=report;wave73ShowJourney(report);return report}
  wave73JourneyState.running=true;const originalView=globalThis.marketingOpsState?.view||'home';const legacyWasVisible=!document.querySelector('main.shell')?.classList.contains('marketing-ops-hidden');const views=[];try{for(const view of WAVE73_VIEWS)views.push(await wave73InspectView(view))}finally{if(legacyWasVisible&&typeof globalThis.opsShowLegacy==='function')globalThis.opsShowLegacy();else if(typeof globalThis.opsShowView==='function')globalThis.opsShowView(originalView);wave73JourneyState.running=false;wave73InstallJourneyAction()}
  const pass=views.filter(row=>row.status==='PASS').length,report={ready:pass===views.length,total:views.length,pass,companyName:company.name,companyId:company.id,views,checkedAt:new Date().toISOString(),safety:{submittedForms:false,externalActions:false,providerActivation:false}};wave73JourneyState.last=report;wave73ShowJourney(report);window.dispatchEvent(new CustomEvent('wave73-journey-complete',{detail:report}));return report
}
globalThis.wave73RunJourneyCheck=wave73RunJourneyCheck;globalThis.wave73JourneyState=wave73JourneyState;window.addEventListener('wave73-entry-ready',()=>wave73InstallJourneyAction());window.addEventListener('marketing-ops-refreshed',()=>wave73InstallJourneyAction());if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(wave73InstallJourneyAction,0),{once:true});else setTimeout(wave73InstallJourneyAction,0);
