const wave47State={metaStatus:null,workspace:null,paidMedia:[],loadingWorkspace:false,loadingPaid:false};
const wave47PreviousRenderMarketingOps=renderMarketingOps;
const wave47PreviousRefreshMarketingOps=refreshMarketingOps;

function wave47Styles(){
  if(document.querySelector('#wave47-product-shell-style'))return;
  const style=document.createElement('style');style.id='wave47-product-shell-style';style.textContent=`
  .wave47-company-context{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.wave47-context-status{font-size:9px;padding:5px 8px;border-radius:999px;background:#efede7}.wave47-context-status.ok{background:#e6f1e8}.wave47-company-hero{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(260px,.8fr);gap:12px;padding:16px;border:1px solid #d9d5cc;border-radius:14px;background:#fff}.wave47-company-title{font-size:24px;margin:3px 0}.wave47-health{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.wave47-health div{padding:10px;border:1px solid #e5e1d9;border-radius:10px;display:grid;gap:3px}.wave47-health strong{font-size:11px}.wave47-health span{font-size:9px;color:#706c65}.wave47-path{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.wave47-path button{min-height:88px;text-align:left;padding:11px;display:grid;align-content:start;gap:4px}.wave47-path strong{font-size:11px}.wave47-path span{font-size:9px;color:#706c65;line-height:1.35}.wave47-setup-grid{display:grid;grid-template-columns:minmax(260px,.75fr) minmax(420px,1.4fr);gap:12px}.wave47-company-card{border:1px solid #dedbd2;border-radius:11px;padding:11px;background:#fff;display:grid;gap:5px;cursor:pointer}.wave47-company-card.active{outline:2px solid #171717}.wave47-company-card small{color:#706c65}.wave47-connection-status{display:flex;gap:7px;flex-wrap:wrap}.wave47-connection-status span{padding:5px 8px;border-radius:999px;background:#efede7;font-size:9px}.wave47-connection-status span.ok{background:#e6f1e8}.wave47-integration-actions{display:flex;gap:7px;flex-wrap:wrap}.wave47-studio-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px}.wave47-studio-card{padding:15px;border:1px solid #dedbd2;border-radius:13px;background:#fff;display:grid;gap:9px}.wave47-studio-number{font-size:28px}.wave47-paid-layout{display:grid;grid-template-columns:minmax(380px,1.2fr) minmax(300px,.8fr);gap:12px}.wave47-form{display:grid;gap:9px}.wave47-form .two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.wave47-paid-list{display:grid;gap:8px}.wave47-paid-row{border:1px solid #dedbd2;border-radius:11px;padding:11px;background:#fff;display:grid;gap:6px}.wave47-paid-row .meta{font-size:9px;color:#706c65}.wave47-safety{padding:10px;border:1px solid #d9d5cc;border-radius:10px;background:#f5f2eb;font-size:10px}.marketing-ops-nav{overflow:auto}.marketing-ops-nav button small{opacity:.55}.marketing-ops-company-select select{min-width:190px}
  @media(max-width:950px){.wave47-company-hero,.wave47-setup-grid,.wave47-paid-layout,.wave47-studio-grid{grid-template-columns:1fr}.wave47-path{grid-template-columns:1fr 1fr}.wave47-health{grid-template-columns:1fr}.wave47-form .two{grid-template-columns:1fr}}
  `;document.head.append(style)
}

function wave47Company(){return opsSelectedCompany()}
function wave47PersistCompany(id){try{localStorage.setItem('marketingOpsCompany',id||'')}catch(_err){}}
function wave47EnsureCompanySelection(){
  const rows=(marketingOpsState.companies||[]).filter(row=>row.active!==false);if(!rows.length){marketingOpsState.selectedCompanyId=null;return false}
  if(rows.some(row=>row.id===marketingOpsState.selectedCompanyId)){wave47PersistCompany(marketingOpsState.selectedCompanyId);return false}
  let saved='';try{saved=localStorage.getItem('marketingOpsCompany')||''}catch(_err){}
  const next=rows.find(row=>row.id===saved)||rows[0];const changed=marketingOpsState.selectedCompanyId!==next.id;marketingOpsState.selectedCompanyId=next.id;wave47PersistCompany(next.id);return changed
}

fillCompanyFilter=function(){
  const select=document.querySelector('#marketing-ops-company-filter');if(!select)return;wave47EnsureCompanySelection();select.replaceChildren();
  if(!marketingOpsState.companies.length){const empty=opsEl('option','','Crea una empresa');empty.value='';select.append(empty);select.disabled=true;return}
  select.disabled=false;for(const company of marketingOpsState.companies){const option=opsEl('option','',company.name);option.value=company.id;select.append(option)}select.value=marketingOpsState.selectedCompanyId||marketingOpsState.companies[0].id;
  const label=select.closest('label');if(label&&label.childNodes[0])label.childNodes[0].textContent='Empresa activa';
}

async function wave47RefreshMeta(){
  try{wave47State.metaStatus=await opsApi('/api/meta/status')}catch(_err){wave47State.metaStatus=null}
}

refreshMarketingOps=async function(forceMeta=false){
  await wave47PreviousRefreshMarketingOps(forceMeta);const changed=wave47EnsureCompanySelection();fillCompanyFilter();
  if(changed)await wave47PreviousRefreshMarketingOps(forceMeta);
  await wave47RefreshMeta();if(forceMeta||marketingOpsState.view==='companies'||marketingOpsState.view==='pauta')await refreshOpsMetaAssets();
  wave47SyncTopContext();renderMarketingOps()
}

function wave47SyncTopContext(){
  const select=document.querySelector('#marketing-ops-company-filter');if(select&&marketingOpsState.selectedCompanyId)select.value=marketingOpsState.selectedCompanyId;
  const top=document.querySelector('.marketing-ops-top');if(!top)return;let status=top.querySelector('.wave47-company-context');if(!status){status=opsEl('div','wave47-company-context');top.append(status)}status.replaceChildren();const company=wave47Company();if(!company)return;
  const meta=opsEl('span',`wave47-context-status ${wave47State.metaStatus?.configured?'ok':''}`,wave47State.metaStatus?.configured?'Meta conectado':'Meta sin conectar');const assets=opsEl('span',`wave47-context-status ${company.facebook_page_id||company.instagram_id?'ok':''}`,company.facebook_page_id||company.instagram_id?'Redes asociadas':'Sin redes asociadas');const ads=opsEl('span',`wave47-context-status ${company.ad_account_id?'ok':''}`,company.ad_account_id?'Pauta configurada':'Sin cuenta Ads');status.append(meta,assets,ads)
}

function wave47EnsureNavigation(){
  const nav=document.querySelector('.marketing-ops-nav');if(!nav)return;const items=[
    ['home','Inicio'],['campaigns','Campañas'],['pauta','Pauta'],['calendar','Calendario'],['publish','Publicar'],['video','Video Studio'],['content','Contenido'],['crm','CRM'],['audiences','Audiencias'],['analytics','Analítica'],['inbox','Bandeja'],['companies','Empresas & Meta']
  ];nav.replaceChildren();for(const [view,label] of items){const button=opsEl('button','',label);button.type='button';button.dataset.opsView=view;button.addEventListener('click',()=>view==='content'?opsShowLegacy():opsShowView(view));nav.append(button)}
  nav.querySelector(`[data-ops-view="${marketingOpsState.view}"]`)?.classList.add('active')
}

function wave47Status(company){return {meta:Boolean(wave47State.metaStatus?.configured),social:Boolean(company?.facebook_page_id||company?.instagram_id),ads:Boolean(company?.ad_account_id)}}
function wave47Quick(label,view,copy){const button=opsEl('button','','');button.type='button';button.append(opsEl('strong','',label),opsEl('span','',copy));button.addEventListener('click',()=>view==='content'?opsShowLegacy():opsShowView(view));return button}

renderOpsHome=function(root){
  const company=wave47Company();if(!company){const section=opsEl('section','marketing-ops-section');section.append(opsEl('p','eyebrow','PRIMER PASO'),opsEl('h3','','Crea tu primera empresa'),opsEl('p','muted','La empresa es el contexto central para campañas, redes, pauta, contenido, CRM y analítica.'));const button=opsEl('button','primary','Crear empresa');button.addEventListener('click',()=>opsShowView('companies'));section.append(button);root.append(section);return}
  const health=wave47Status(company),hero=opsEl('section','wave47-company-hero'),copy=opsEl('div','');copy.append(opsEl('p','eyebrow','EMPRESA ACTIVA'),opsEl('h3','wave47-company-title',company.name),opsEl('p','muted','Un solo contexto para planear, crear, distribuir, convertir y medir.'));const actions=opsEl('div','marketing-ops-actions');[['+ Crear campaña','campaigns'],['Abrir Video Studio','video'],['Preparar pauta','pauta']].forEach(([label,view],index)=>{const b=opsEl('button',index===0?'primary':'',label);b.addEventListener('click',()=>opsShowView(view));actions.append(b)});copy.append(actions);const h=opsEl('div','wave47-health');h.append(wave47HealthCard('Meta',health.meta?'Conectado':'Pendiente',health.meta?'Credencial disponible en Keychain':'Conecta desde Empresas & Meta'),wave47HealthCard('Redes',health.social?'Asociadas':'Pendiente',company.facebook_page_name||company.instagram_username||'Selecciona Página/Instagram'),wave47HealthCard('Pauta',health.ads?'Cuenta lista':'Pendiente',company.ad_account_name||'Asocia una cuenta publicitaria'));hero.append(copy,h);root.append(hero);
  const data=marketingOpsState.dashboard||{summary:{}},summary=data.summary||{},crm=data.crm||{},grid=opsEl('div','marketing-ops-grid');grid.append(opsMetric('HOY',data.scheduled_today||0,'publicaciones programadas'),opsMetric('CRM',crm.pending_activities||0,'seguimientos pendientes'),opsMetric('BORRADORES',summary.draft||0,'contenidos por revisar'),opsMetric('ATENCIÓN',(summary.failed||0)+(data.overdue||0)+(crm.overdue_activities||0),'errores o vencidos'));root.append(grid);
  const path=opsEl('div','wave47-path');path.append(wave47Quick('1 · Planear','campaigns','Campañas, objetivos y audiencias'),wave47Quick('2 · Crear','video','Video, clips, transcripción y renders'),wave47Quick('3 · Distribuir','calendar','Orgánico y calendario editorial'),wave47Quick('4 · Convertir','crm','Contactos, oportunidades y seguimiento'),wave47Quick('5 · Optimizar','analytics','Resultados orgánicos y aprendizaje'));root.append(path);
  if(typeof dailyFocus==='function')dailyFocus(root);const next=opsEl('section','marketing-ops-section');const head=opsEl('div','marketing-ops-section-head');head.append(opsEl('div','',''));head.firstChild.append(opsEl('p','eyebrow','PRÓXIMAS'),opsEl('h3','','Publicaciones programadas'));next.append(head);const list=opsEl('div','marketing-ops-list');for(const row of data.upcoming||[]){const item=opsEl('div','marketing-ops-row');const left=opsEl('div','');left.append(opsEl('strong','',row.company_name||company.name),opsEl('p','',row.message||'(sin copy)'));const middle=opsEl('div','');middle.append(opsEl('span','status',opsStatusLabel(row.status)),opsEl('p','',opsDate(row.scheduled_for)));item.append(left,middle,opsEl('span','marketing-ops-badge',row.channel==='instagram'?'Instagram':'Facebook'));list.append(item)}if(!(data.upcoming||[]).length)list.append(opsEmpty('No hay publicaciones futuras programadas para esta empresa.'));next.append(list);root.append(next);wave47HydrateWorkspaceSummary(root)
}
function wave47HealthCard(title,value,copy){const card=opsEl('div','');card.append(opsEl('strong','',`${title} · ${value}`),opsEl('span','',copy));return card}

async function wave47HydrateWorkspaceSummary(root){
  const company=wave47Company();if(!company)return;try{const info=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/workspace`);wave47State.workspace=info;let card=root.querySelector('#wave47-workspace-summary');if(!card){card=opsEl('section','marketing-ops-section');card.id='wave47-workspace-summary';root.append(card)}card.replaceChildren();card.append(opsEl('p','eyebrow','MARKETING STUDIO'),opsEl('h3','',info.project_id?'Workspace creativo listo':'Workspace creativo aún no creado'),opsEl('p','muted',info.project_id?`${info.assets} assets · ${info.renders} renders · ${info.paid_media} planes de pauta`:'Se crea de forma explícita la primera vez que abres Video Studio o Pauta.'));const b=opsEl('button','','Abrir Video Studio');b.addEventListener('click',()=>opsShowView('video'));card.append(b)}catch(_err){}
}

function renderWave47Companies(root){
  const grid=opsEl('div','wave47-setup-grid'),left=opsEl('section','marketing-ops-section'),right=opsEl('section','marketing-ops-section');left.append(opsEl('p','eyebrow','EMPRESAS'),opsEl('h3','','Marcas que administras'),opsEl('p','muted','Selecciona una empresa: todo el sistema trabajará desde ese contexto.'));
  const create=opsEl('form','marketing-ops-form'),label=opsEl('label','','Nueva empresa'),input=document.createElement('input');input.required=true;input.placeholder='Ej. Greenatics';label.append(input);const add=opsEl('button','primary','Crear empresa');create.append(label,add);create.addEventListener('submit',async event=>{event.preventDefault();try{const row=await opsApi('/api/companies',{method:'POST',body:{name:input.value.trim()}});marketingOpsState.selectedCompanyId=row.id;wave47PersistCompany(row.id);input.value='';await refreshMarketingOps(true);opsShowView('companies')}catch(err){opsToast(err.message)}});left.append(create);
  const list=opsEl('div','marketing-ops-company-list');for(const company of marketingOpsState.companies){const card=opsEl('article',`wave47-company-card ${company.id===marketingOpsState.selectedCompanyId?'active':''}`);card.append(opsEl('strong','',company.name),opsEl('small','',`${company.facebook_page_id?'Facebook ✓':'Facebook —'} · ${company.instagram_id?'Instagram ✓':'Instagram —'} · ${company.ad_account_id?'Ads ✓':'Ads —'}`));card.addEventListener('click',async()=>{marketingOpsState.selectedCompanyId=company.id;wave47PersistCompany(company.id);fillCompanyFilter();await refreshMarketingOps(true);opsShowView('companies')});list.append(card)}if(!marketingOpsState.companies.length)list.append(opsEmpty('Crea la primera empresa.'));left.append(list);renderWave47Integration(right,wave47Company());grid.append(left,right);root.append(grid)
}

function renderWave47Integration(root,company){
  root.append(opsEl('p','eyebrow','INTEGRACIONES'),opsEl('h3','',company?`Meta · ${company.name}`:'Selecciona una empresa'));if(!company){root.append(opsEmpty('Selecciona una empresa para configurar Meta.'));return}
  const status=wave47State.metaStatus||{},chips=opsEl('div','wave47-connection-status');chips.append(opsEl('span',status.configured?'ok':'',status.configured?'Meta conectado':'Meta sin conectar'),opsEl('span',company.facebook_page_id?'ok':'',company.facebook_page_name||'Facebook sin asociar'),opsEl('span',company.instagram_id?'ok':'',company.instagram_username?`@${company.instagram_username}`:'Instagram sin asociar'),opsEl('span',company.ad_account_id?'ok':'',company.ad_account_name||'Ads sin asociar'));root.append(chips);
  if(!status.configured){const form=opsEl('form','marketing-ops-form'),tokenLabel=opsEl('label','','Meta access token'),token=document.createElement('input');token.type='password';token.autocomplete='off';token.placeholder='Pega el token una sola vez';tokenLabel.append(token);form.append(tokenLabel,opsEl('p','muted','Se valida contra Meta y en Mac se guarda en Keychain. No se escribe dentro del proyecto.'));const connect=opsEl('button','primary','Conectar Meta');form.append(connect);form.addEventListener('submit',async event=>{event.preventDefault();if(!token.value.trim()){opsToast('Pega un access token');return}connect.disabled=true;try{await opsApi('/api/meta/connection',{method:'POST',body:{access_token:token.value.trim()}});token.value='';opsToast('Meta conectado');await refreshMarketingOps(true);opsShowView('companies')}catch(err){opsToast(err.message)}finally{connect.disabled=false}});root.append(form);return}
  const actions=opsEl('div','wave47-integration-actions');const refresh=opsEl('button','','Actualizar activos');refresh.addEventListener('click',async()=>{await refreshMarketingOps(true);opsShowView('companies')});actions.append(refresh);if(status.credential_source==='keychain'){const disconnect=opsEl('button','','Desconectar Meta');disconnect.addEventListener('click',async()=>{if(!confirm('¿Desconectar la credencial Meta guardada en Keychain? Las asociaciones de empresa se conservarán hasta que las cambies.'))return;try{await opsApi('/api/meta/connection',{method:'DELETE'});opsToast('Meta desconectado');await refreshMarketingOps(true);opsShowView('companies')}catch(err){opsToast(err.message)}});actions.append(disconnect)}root.append(actions);
  const form=opsEl('form','marketing-ops-form'),pageLabel=opsEl('label','','Página de Facebook / Instagram'),page=document.createElement('select');let empty=opsEl('option','','Sin asociar');empty.value='';page.append(empty);for(const row of marketingOpsState.metaPages||[]){const option=opsEl('option','',`${row.name||row.id}${row.instagram?` · @${row.instagram.username||row.instagram.id}`:''}`);option.value=row.id;option.selected=row.id===company.facebook_page_id;page.append(option)}pageLabel.append(page);const adLabel=opsEl('label','','Cuenta publicitaria'),ad=document.createElement('select');empty=opsEl('option','','Sin asociar');empty.value='';ad.append(empty);for(const row of marketingOpsState.metaAdAccounts||[]){const option=opsEl('option','',`${row.name||row.id}${row.currency?` · ${row.currency}`:''}`);option.value=row.id;option.selected=row.id===company.ad_account_id;ad.append(option)}adLabel.append(ad);form.append(pageLabel,adLabel);const save=opsEl('button','primary','Guardar asociaciones');form.append(save);form.addEventListener('submit',async event=>{event.preventDefault();const selectedPage=(marketingOpsState.metaPages||[]).find(row=>row.id===page.value),selectedAd=(marketingOpsState.metaAdAccounts||[]).find(row=>row.id===ad.value);try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}`,{method:'PATCH',body:{facebook_page_id:selectedPage?.id||null,facebook_page_name:selectedPage?.name||null,instagram_id:selectedPage?.instagram?.id||null,instagram_username:selectedPage?.instagram?.username||null,ad_account_id:selectedAd?.id||null,ad_account_name:selectedAd?.name||null}});opsToast('Activos Meta asociados a la empresa');await refreshMarketingOps(true);opsShowView('companies')}catch(err){opsToast(err.message)}});root.append(form)
}

function renderWave47Video(root){
  const company=wave47Company(),section=opsEl('section','marketing-ops-section');section.append(opsEl('p','eyebrow','CREATIVE STUDIO'),opsEl('h3','',company?`Video Studio · ${company.name}`:'Video Studio'),opsEl('p','muted','Edición local con FFmpeg + Whisper: carga, transcripción, clips, timeline, formatos y renders desde el workspace de la empresa.'));if(!company){section.append(opsEmpty('Selecciona o crea una empresa primero.'));root.append(section);return}const grid=opsEl('div','wave47-studio-grid'),studio=opsEl('article','wave47-studio-card'),quick=opsEl('article','wave47-studio-card');studio.append(opsEl('p','eyebrow','EDITOR COMPLETO'),opsEl('strong','wave47-studio-number','Video Studio'),opsEl('p','muted','Preview, timeline, overlays, subtítulos, audio, reframe 9:16/16:9/1:1/4:5 y render reproducible.'));const open=opsEl('button','primary','Abrir Video Studio');open.addEventListener('click',()=>wave47OpenStudio(false));studio.append(open);quick.append(opsEl('p','eyebrow','FLUJO RÁPIDO'),opsEl('strong','wave47-studio-number','Nuevo video'),opsEl('p','muted','Abre el Studio de esta empresa y lanza directamente la carga de un video para empezar a crear clips.'));const upload=opsEl('button','','Cargar video y empezar');upload.addEventListener('click',()=>wave47OpenStudio(true));quick.append(upload);grid.append(studio,quick);section.append(grid);const summary=opsEl('div','wave47-safety','El proyecto creativo queda ligado a esta empresa y se reutiliza en futuras sesiones. Los renders pueden alimentar campañas, publicación y pauta sin duplicar motores.');section.append(summary);root.append(section);wave47LoadWorkspace(section)
}
async function wave47LoadWorkspace(root){const company=wave47Company();if(!company)return;try{const info=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/workspace`);wave47State.workspace=info;const status=opsEl('div','marketing-ops-grid');status.append(opsMetric('ASSETS',info.assets,'medios en Studio'),opsMetric('RENDERS',info.renders,'exportaciones'),opsMetric('PAUTA',info.paid_media,'planes asociados'));root.append(status)}catch(err){opsToast(err.message)}}
async function wave47OpenStudio(autoUpload){const company=wave47Company();if(!company)return;try{const info=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/workspace`,{method:'POST',body:{}});opsShowLegacy();await selectProject(info.project_id);if(autoUpload){if(typeof globalThis.quickUploadVideo==='function')setTimeout(()=>globalThis.quickUploadVideo(),50);else opsToast('Studio abierto. Usa Seleccionar archivos para cargar video.')}}catch(err){opsToast(err.message)}}

function wave47Input(labelText,type='text',value=''){const label=opsEl('label','',labelText),input=document.createElement('input');input.type=type;input.value=value;label.append(input);return [label,input]}
function renderWave47Pauta(root){
  const company=wave47Company(),section=opsEl('section','marketing-ops-section');section.append(opsEl('p','eyebrow','PAUTA META'),opsEl('h3','',company?`Paid Media · ${company.name}`:'Paid Media'),opsEl('p','muted','Planea y crea Campaign + Ad Set + Creative + Ad dentro de Meta, siempre en PAUSED. La activación y el gasto no están habilitados desde este gate.'));if(!company){section.append(opsEmpty('Selecciona una empresa.'));root.append(section);return}const status=wave47Status(company);if(!status.meta||!status.ads||!company.facebook_page_id){const warning=opsEl('div','wave47-safety','Antes de preparar pauta conecta Meta y asocia una Página y una cuenta publicitaria a esta empresa.');const go=opsEl('button','primary','Configurar Meta');go.addEventListener('click',()=>opsShowView('companies'));warning.append(document.createElement('br'),go);section.append(warning);root.append(section);wave47LoadPaidMedia(root);return}
  const layout=opsEl('div','wave47-paid-layout'),formCard=opsEl('div',''),listCard=opsEl('div','');formCard.append(wave47PaidForm(company));listCard.append(opsEl('p','eyebrow','PLANES'),opsEl('h3','','Borradores y campañas PAUSED'));const list=opsEl('div','wave47-paid-list');list.id='wave47-paid-list';list.append(opsEl('p','muted','Cargando…'));listCard.append(list);layout.append(formCard,listCard);section.append(layout,opsEl('div','wave47-safety',`Cuenta Ads: ${company.ad_account_name||company.ad_account_id} · Página: ${company.facebook_page_name||company.facebook_page_id}. La empresa activa fija estos activos: el formulario no puede redirigir la pauta a otra cuenta.`));root.append(section);wave47LoadPaidMedia(root)
}
function wave47PaidForm(company){
  const form=opsEl('form','wave47-form'),first=opsEl('div','two'),[campaignL,campaign]=wave47Input('Campaña'),objectiveL=opsEl('label','','Objetivo'),objective=document.createElement('select');[['OUTCOME_AWARENESS','Reconocimiento'],['OUTCOME_TRAFFIC','Tráfico'],['OUTCOME_ENGAGEMENT','Interacción'],['OUTCOME_LEADS','Leads'],['OUTCOME_SALES','Ventas']].forEach(([v,l])=>{const o=opsEl('option','',l);o.value=v;objective.append(o)});objectiveL.append(objective);campaign.required=true;campaign.placeholder='Ej. Leads Medellín agosto';first.append(campaignL,objectiveL);form.append(first);
  const second=opsEl('div','two'),[adsetL,adset]=wave47Input('Ad Set'),[budgetL,budget]=wave47Input('Presupuesto diario','number','10000');adset.required=true;adset.placeholder='Colombia 25–55';budget.min='1';budget.required=true;second.append(adsetL,budgetL);form.append(second);
  const targeting=opsEl('div','two'),[countriesL,countries]=wave47Input('Países','text','CO'),[ageMinL,ageMin]=wave47Input('Edad mínima','number','21');ageMin.min='18';ageMin.max='65';targeting.append(countriesL,ageMinL);form.append(targeting);const targeting2=opsEl('div','two'),[ageMaxL,ageMax]=wave47Input('Edad máxima','number','55'),optimizationL=opsEl('label','','Optimización'),optimization=document.createElement('select');[['LINK_CLICKS','Link clicks'],['LANDING_PAGE_VIEWS','Landing page views'],['IMPRESSIONS','Impressions'],['REACH','Reach']].forEach(([v,l])=>{const o=opsEl('option','',l);o.value=v;optimization.append(o)});optimizationL.append(optimization);targeting2.append(ageMaxL,optimizationL);form.append(targeting2);
  const creative=opsEl('div','two'),[creativeL,creativeName]=wave47Input('Creative'),[adL,adName]=wave47Input('Anuncio');creativeName.required=true;creativeName.placeholder='Creative A';adName.required=true;adName.placeholder='Anuncio A';creative.append(creativeL,adL);form.append(creative);const messageL=opsEl('label','','Copy'),message=document.createElement('textarea');message.rows=3;message.required=true;message.placeholder='Texto principal del anuncio';messageL.append(message);form.append(messageL);const [linkL,link]=wave47Input('URL destino','url'),[pictureL,picture]=wave47Input('Imagen pública','url');link.required=true;picture.required=true;link.placeholder='https://...';picture.placeholder='https://.../creative.jpg';form.append(linkL,pictureL);const ctaL=opsEl('label','','CTA'),cta=document.createElement('select');[['LEARN_MORE','Más información'],['SHOP_NOW','Comprar'],['SIGN_UP','Registrarse'],['CONTACT_US','Contactar'],['GET_OFFER','Ver oferta']].forEach(([v,l])=>{const o=opsEl('option','',l);o.value=v;cta.append(o)});ctaL.append(cta);form.append(ctaL);const save=opsEl('button','primary','Guardar borrador de pauta');form.append(save);form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;try{const payload={campaign_name:campaign.value.trim(),campaign_objective:objective.value,special_ad_categories:[],adset_name:adset.value.trim(),daily_budget:Number(budget.value),optimization_goal:optimization.value,targeting:{geo_locations:{countries:countries.value.split(',').map(v=>v.trim().toUpperCase()).filter(Boolean)},age_min:Number(ageMin.value),age_max:Number(ageMax.value)},creative_name:creativeName.value.trim(),message:message.value.trim(),link_url:link.value.trim(),picture_url:picture.value.trim(),call_to_action:cta.value,ad_name:adName.value.trim()};await opsApi(`/api/companies/${encodeURIComponent(company.id)}/paid-media`,{method:'POST',body:payload});opsToast('Borrador de pauta guardado');form.reset();budget.value='10000';countries.value='CO';ageMin.value='21';ageMax.value='55';await wave47LoadPaidMedia(document)}catch(err){opsToast(err.message)}finally{save.disabled=false}});return form
}
async function wave47LoadPaidMedia(_root){const company=wave47Company();if(!company)return;try{wave47State.paidMedia=await opsApi(`/api/companies/${encodeURIComponent(company.id)}/paid-media`);const list=document.querySelector('#wave47-paid-list');if(!list)return;list.replaceChildren();for(const row of [...wave47State.paidMedia].reverse()){const card=opsEl('article','wave47-paid-row');card.append(opsEl('strong','',row.campaign_name),opsEl('span','status',row.status),opsEl('div','meta',`${row.campaign_objective} · presupuesto ${row.daily_budget} · ${row.adset_name}`));const actions=opsEl('div','marketing-ops-actions');if(row.status==='DRAFT'){const remote=opsEl('button','primary','Crear en Meta · PAUSED');remote.addEventListener('click',async()=>{if(!confirm('Se crearán Campaign, Ad Set y Ad en Meta con estado PAUSED. No se activará gasto. ¿Continuar?'))return;remote.disabled=true;try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/paid-media/${encodeURIComponent(row.id)}/create-paused`,{method:'POST',body:{}});opsToast('Estructura creada en Meta en PAUSED');await wave47LoadPaidMedia(document)}catch(err){opsToast(err.message)}finally{remote.disabled=false}});const cancel=opsEl('button','','Cancelar borrador');cancel.addEventListener('click',async()=>{if(!confirm('¿Cancelar este borrador local?'))return;try{await opsApi(`/api/companies/${encodeURIComponent(company.id)}/paid-media/${encodeURIComponent(row.id)}`,{method:'DELETE'});await wave47LoadPaidMedia(document)}catch(err){opsToast(err.message)}});actions.append(remote,cancel)}if(row.status==='REMOTE_PAUSED')card.append(opsEl('div','meta',`Meta IDs · Campaign ${row.campaign_id||'—'} · Ad Set ${row.adset_id||'—'} · Ad ${row.ad_id||'—'}`));card.append(actions);list.append(card)}if(!wave47State.paidMedia.length)list.append(opsEmpty('Aún no hay borradores de pauta para esta empresa.'))}catch(err){opsToast(err.message)}}

renderMarketingOps=function(){
  wave47EnsureNavigation();wave47SyncTopContext();if(marketingOpsState.view==='video'){const root=document.querySelector('#marketing-ops-view');if(!root)return;root.replaceChildren();wave47SetTitle('VIDEO STUDIO','Creative Studio','Crea y transforma piezas dentro del contexto de la empresa.');renderWave47Video(root);return}if(marketingOpsState.view==='pauta'){const root=document.querySelector('#marketing-ops-view');if(!root)return;root.replaceChildren();wave47SetTitle('PAUTA','Paid Media','Planifica y crea estructuras Meta seguras, siempre PAUSED.');renderWave47Pauta(root);return}if(marketingOpsState.view==='companies'){const root=document.querySelector('#marketing-ops-view');if(!root)return;root.replaceChildren();wave47SetTitle('EMPRESAS & META','Empresas e integraciones','Selecciona la empresa activa, conecta Meta y asocia sus activos.');renderWave47Companies(root);return}wave47PreviousRenderMarketingOps();wave47EnsureNavigation();wave47SyncTopContext()
}
function wave47SetTitle(eyebrow,title,subtitle){document.querySelector('#marketing-ops-eyebrow').textContent=eyebrow;document.querySelector('#marketing-ops-title').textContent=title;document.querySelector('#marketing-ops-subtitle').textContent=subtitle}

wave47Styles();wave47EnsureNavigation();const companyChanged=wave47EnsureCompanySelection();fillCompanyFilter();wave47RefreshMeta().then(async()=>{if(companyChanged)await refreshMarketingOps(true);else{wave47SyncTopContext();renderMarketingOps()}});
